/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreatePrice,
  CreateProduct,
  PriceArchiveResponseOutput,
  PricePageResponseOutput,
  PriceResponseOutput,
  ProductArchiveResponseOutput,
  ProductPageResponseOutput,
  ProductResponseOutput,
  UpdatePrice,
  UpdateProduct,
} from '../models/index';
import {
    CreatePriceFromJSON,
    CreatePriceToJSON,
    CreateProductFromJSON,
    CreateProductToJSON,
    PriceArchiveResponseOutputFromJSON,
    PriceArchiveResponseOutputToJSON,
    PricePageResponseOutputFromJSON,
    PricePageResponseOutputToJSON,
    PriceResponseOutputFromJSON,
    PriceResponseOutputToJSON,
    ProductArchiveResponseOutputFromJSON,
    ProductArchiveResponseOutputToJSON,
    ProductPageResponseOutputFromJSON,
    ProductPageResponseOutputToJSON,
    ProductResponseOutputFromJSON,
    ProductResponseOutputToJSON,
    UpdatePriceFromJSON,
    UpdatePriceToJSON,
    UpdateProductFromJSON,
    UpdateProductToJSON,
} from '../models/index';

export interface ArchivePriceRequest {
    priceId: string;
    idempotencyKey?: string;
}

export interface ArchiveProductRequest {
    productId: string;
    idempotencyKey?: string;
}

export interface CreatePriceRequest {
    createPrice: CreatePrice;
    idempotencyKey?: string;
}

export interface CreateProductRequest {
    createProduct: CreateProduct;
    idempotencyKey?: string;
}

export interface GetPriceRequest {
    priceId: string;
    idempotencyKey?: string;
}

export interface GetProductRequest {
    productId: string;
    idempotencyKey?: string;
}

export interface ListPricesRequest {
    productId?: string;
    active?: string;
    limit?: string;
    cursor?: string;
    idempotencyKey?: string;
}

export interface ListProductsRequest {
    active?: string;
    limit?: string;
    cursor?: string;
    idempotencyKey?: string;
}

export interface UpdatePriceRequest {
    priceId: string;
    updatePrice: UpdatePrice;
    idempotencyKey?: string;
}

export interface UpdateProductRequest {
    productId: string;
    updateProduct: UpdateProduct;
    idempotencyKey?: string;
}

export interface UploadProductImageRequest {
    productId: string;
    file: Blob;
    idempotencyKey?: string;
}

/**
 * 
 */
export class CatalogApi extends runtime.BaseAPI {

    /**
     * Archive a price (soft-delete: sets active=false).
     */
    async archivePriceRaw(requestParameters: ArchivePriceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PriceArchiveResponseOutput>> {
        if (requestParameters['priceId'] == null) {
            throw new runtime.RequiredError(
                'priceId',
                'Required parameter "priceId" was null or undefined when calling archivePrice().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/catalog/prices/{priceId}`;
        urlPath = urlPath.replace(`{${"priceId"}}`, encodeURIComponent(String(requestParameters['priceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PriceArchiveResponseOutputFromJSON(jsonValue));
    }

    /**
     * Archive a price (soft-delete: sets active=false).
     */
    async archivePrice(requestParameters: ArchivePriceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PriceArchiveResponseOutput> {
        const response = await this.archivePriceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Archive a product (soft-delete: sets active=false, cascades to prices).
     */
    async archiveProductRaw(requestParameters: ArchiveProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductArchiveResponseOutput>> {
        if (requestParameters['productId'] == null) {
            throw new runtime.RequiredError(
                'productId',
                'Required parameter "productId" was null or undefined when calling archiveProduct().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/catalog/products/{productId}`;
        urlPath = urlPath.replace(`{${"productId"}}`, encodeURIComponent(String(requestParameters['productId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductArchiveResponseOutputFromJSON(jsonValue));
    }

    /**
     * Archive a product (soft-delete: sets active=false, cascades to prices).
     */
    async archiveProduct(requestParameters: ArchiveProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductArchiveResponseOutput> {
        const response = await this.archiveProductRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new price for a product. Product must be active. Idempotency-Key required on retries.
     */
    async createPriceRaw(requestParameters: CreatePriceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PriceResponseOutput>> {
        if (requestParameters['createPrice'] == null) {
            throw new runtime.RequiredError(
                'createPrice',
                'Required parameter "createPrice" was null or undefined when calling createPrice().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/catalog/prices`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePriceToJSON(requestParameters['createPrice']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PriceResponseOutputFromJSON(jsonValue));
    }

    /**
     * Create a new price for a product. Product must be active. Idempotency-Key required on retries.
     */
    async createPrice(requestParameters: CreatePriceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PriceResponseOutput> {
        const response = await this.createPriceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new product for the merchant business. Idempotency-Key required on retries.
     */
    async createProductRaw(requestParameters: CreateProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductResponseOutput>> {
        if (requestParameters['createProduct'] == null) {
            throw new runtime.RequiredError(
                'createProduct',
                'Required parameter "createProduct" was null or undefined when calling createProduct().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/catalog/products`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateProductToJSON(requestParameters['createProduct']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductResponseOutputFromJSON(jsonValue));
    }

    /**
     * Create a new product for the merchant business. Idempotency-Key required on retries.
     */
    async createProduct(requestParameters: CreateProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductResponseOutput> {
        const response = await this.createProductRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a single price by ID.
     */
    async getPriceRaw(requestParameters: GetPriceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PriceResponseOutput>> {
        if (requestParameters['priceId'] == null) {
            throw new runtime.RequiredError(
                'priceId',
                'Required parameter "priceId" was null or undefined when calling getPrice().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/catalog/prices/{priceId}`;
        urlPath = urlPath.replace(`{${"priceId"}}`, encodeURIComponent(String(requestParameters['priceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PriceResponseOutputFromJSON(jsonValue));
    }

    /**
     * Get a single price by ID.
     */
    async getPrice(requestParameters: GetPriceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PriceResponseOutput> {
        const response = await this.getPriceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a single product by ID.
     */
    async getProductRaw(requestParameters: GetProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductResponseOutput>> {
        if (requestParameters['productId'] == null) {
            throw new runtime.RequiredError(
                'productId',
                'Required parameter "productId" was null or undefined when calling getProduct().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/catalog/products/{productId}`;
        urlPath = urlPath.replace(`{${"productId"}}`, encodeURIComponent(String(requestParameters['productId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductResponseOutputFromJSON(jsonValue));
    }

    /**
     * Get a single product by ID.
     */
    async getProduct(requestParameters: GetProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductResponseOutput> {
        const response = await this.getProductRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List prices for the merchant business (cursor pagination, optional ?productId= filter).
     */
    async listPricesRaw(requestParameters: ListPricesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PricePageResponseOutput>> {
        const queryParameters: any = {};

        if (requestParameters['productId'] != null) {
            queryParameters['productId'] = requestParameters['productId'];
        }

        if (requestParameters['active'] != null) {
            queryParameters['active'] = requestParameters['active'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/catalog/prices`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PricePageResponseOutputFromJSON(jsonValue));
    }

    /**
     * List prices for the merchant business (cursor pagination, optional ?productId= filter).
     */
    async listPrices(requestParameters: ListPricesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PricePageResponseOutput> {
        const response = await this.listPricesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List products for the merchant business (cursor pagination, active=true default).
     */
    async listProductsRaw(requestParameters: ListProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductPageResponseOutput>> {
        const queryParameters: any = {};

        if (requestParameters['active'] != null) {
            queryParameters['active'] = requestParameters['active'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/catalog/products`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductPageResponseOutputFromJSON(jsonValue));
    }

    /**
     * List products for the merchant business (cursor pagination, active=true default).
     */
    async listProducts(requestParameters: ListProductsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductPageResponseOutput> {
        const response = await this.listProductsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update mutable fields on a price. Idempotency-Key required on retries.
     */
    async updatePriceRaw(requestParameters: UpdatePriceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PriceResponseOutput>> {
        if (requestParameters['priceId'] == null) {
            throw new runtime.RequiredError(
                'priceId',
                'Required parameter "priceId" was null or undefined when calling updatePrice().'
            );
        }

        if (requestParameters['updatePrice'] == null) {
            throw new runtime.RequiredError(
                'updatePrice',
                'Required parameter "updatePrice" was null or undefined when calling updatePrice().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/catalog/prices/{priceId}`;
        urlPath = urlPath.replace(`{${"priceId"}}`, encodeURIComponent(String(requestParameters['priceId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdatePriceToJSON(requestParameters['updatePrice']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PriceResponseOutputFromJSON(jsonValue));
    }

    /**
     * Update mutable fields on a price. Idempotency-Key required on retries.
     */
    async updatePrice(requestParameters: UpdatePriceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PriceResponseOutput> {
        const response = await this.updatePriceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update mutable fields on a product. Idempotency-Key required on retries.
     */
    async updateProductRaw(requestParameters: UpdateProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductResponseOutput>> {
        if (requestParameters['productId'] == null) {
            throw new runtime.RequiredError(
                'productId',
                'Required parameter "productId" was null or undefined when calling updateProduct().'
            );
        }

        if (requestParameters['updateProduct'] == null) {
            throw new runtime.RequiredError(
                'updateProduct',
                'Required parameter "updateProduct" was null or undefined when calling updateProduct().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/catalog/products/{productId}`;
        urlPath = urlPath.replace(`{${"productId"}}`, encodeURIComponent(String(requestParameters['productId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateProductToJSON(requestParameters['updateProduct']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductResponseOutputFromJSON(jsonValue));
    }

    /**
     * Update mutable fields on a product. Idempotency-Key required on retries.
     */
    async updateProduct(requestParameters: UpdateProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductResponseOutput> {
        const response = await this.updateProductRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Upload a product image (multipart \"file\": SVG/PNG/JPEG, max 2 MB). Stores in object storage, sets imageUrl, emits a product.updated audit row.
     */
    async uploadProductImageRaw(requestParameters: UploadProductImageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProductResponseOutput>> {
        if (requestParameters['productId'] == null) {
            throw new runtime.RequiredError(
                'productId',
                'Required parameter "productId" was null or undefined when calling uploadProductImage().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling uploadProductImage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }


        let urlPath = `/v1/catalog/products/{productId}/image`;
        urlPath = urlPath.replace(`{${"productId"}}`, encodeURIComponent(String(requestParameters['productId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProductResponseOutputFromJSON(jsonValue));
    }

    /**
     * Upload a product image (multipart \"file\": SVG/PNG/JPEG, max 2 MB). Stores in object storage, sets imageUrl, emits a product.updated audit row.
     */
    async uploadProductImage(requestParameters: UploadProductImageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProductResponseOutput> {
        const response = await this.uploadProductImageRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
