/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateCheckoutSession,
  CreateCheckoutSession201Response,
} from '../models/index';
import {
    CreateCheckoutSessionFromJSON,
    CreateCheckoutSessionToJSON,
    CreateCheckoutSession201ResponseFromJSON,
    CreateCheckoutSession201ResponseToJSON,
} from '../models/index';

export interface CreateCheckoutSessionRequest {
    createCheckoutSession: CreateCheckoutSession;
    idempotencyKey?: string;
}

/**
 * 
 */
export class CheckoutApi extends runtime.BaseAPI {

    /**
     * Create a checkout session for a price. Returns a cs_ id + a one-time public URL carrying the raw token. Idempotency-Key required on retries.
     */
    async createCheckoutSessionRaw(requestParameters: CreateCheckoutSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateCheckoutSession201Response>> {
        if (requestParameters['createCheckoutSession'] == null) {
            throw new runtime.RequiredError(
                'createCheckoutSession',
                'Required parameter "createCheckoutSession" was null or undefined when calling createCheckoutSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/checkout/sessions`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCheckoutSessionToJSON(requestParameters['createCheckoutSession']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateCheckoutSession201ResponseFromJSON(jsonValue));
    }

    /**
     * Create a checkout session for a price. Returns a cs_ id + a one-time public URL carrying the raw token. Idempotency-Key required on retries.
     */
    async createCheckoutSession(requestParameters: CreateCheckoutSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateCheckoutSession201Response> {
        const response = await this.createCheckoutSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
