/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateCustomer,
  CustomerArchiveResponseOutput,
  CustomerPageResponseOutput,
  CustomerResponseOutput,
  UpdateCustomer,
} from '../models/index';
import {
    CreateCustomerFromJSON,
    CreateCustomerToJSON,
    CustomerArchiveResponseOutputFromJSON,
    CustomerArchiveResponseOutputToJSON,
    CustomerPageResponseOutputFromJSON,
    CustomerPageResponseOutputToJSON,
    CustomerResponseOutputFromJSON,
    CustomerResponseOutputToJSON,
    UpdateCustomerFromJSON,
    UpdateCustomerToJSON,
} from '../models/index';

export interface ArchiveCustomerRequest {
    customerId: string;
    idempotencyKey?: string;
}

export interface CreateCustomerRequest {
    createCustomer: CreateCustomer;
    idempotencyKey?: string;
}

export interface GetCustomerRequest {
    customerId: string;
    idempotencyKey?: string;
}

export interface ListCustomersRequest {
    search?: string;
    status?: string;
    createdFrom?: string;
    createdTo?: string;
    limit?: string;
    cursor?: string;
    idempotencyKey?: string;
}

export interface UpdateCustomerRequest {
    customerId: string;
    updateCustomer: UpdateCustomer;
    idempotencyKey?: string;
}

/**
 * 
 */
export class CustomersApi extends runtime.BaseAPI {

    /**
     * Archive a customer (soft-delete: sets archivedAt).
     */
    async archiveCustomerRaw(requestParameters: ArchiveCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerArchiveResponseOutput>> {
        if (requestParameters['customerId'] == null) {
            throw new runtime.RequiredError(
                'customerId',
                'Required parameter "customerId" was null or undefined when calling archiveCustomer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/customers/{customerId}`;
        urlPath = urlPath.replace(`{${"customerId"}}`, encodeURIComponent(String(requestParameters['customerId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerArchiveResponseOutputFromJSON(jsonValue));
    }

    /**
     * Archive a customer (soft-delete: sets archivedAt).
     */
    async archiveCustomer(requestParameters: ArchiveCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerArchiveResponseOutput> {
        const response = await this.archiveCustomerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new customer for the merchant business. Idempotency-Key required on retries.
     */
    async createCustomerRaw(requestParameters: CreateCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerResponseOutput>> {
        if (requestParameters['createCustomer'] == null) {
            throw new runtime.RequiredError(
                'createCustomer',
                'Required parameter "createCustomer" was null or undefined when calling createCustomer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/customers`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCustomerToJSON(requestParameters['createCustomer']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerResponseOutputFromJSON(jsonValue));
    }

    /**
     * Create a new customer for the merchant business. Idempotency-Key required on retries.
     */
    async createCustomer(requestParameters: CreateCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerResponseOutput> {
        const response = await this.createCustomerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a single customer by ID.
     */
    async getCustomerRaw(requestParameters: GetCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerResponseOutput>> {
        if (requestParameters['customerId'] == null) {
            throw new runtime.RequiredError(
                'customerId',
                'Required parameter "customerId" was null or undefined when calling getCustomer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/customers/{customerId}`;
        urlPath = urlPath.replace(`{${"customerId"}}`, encodeURIComponent(String(requestParameters['customerId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerResponseOutputFromJSON(jsonValue));
    }

    /**
     * Get a single customer by ID.
     */
    async getCustomer(requestParameters: GetCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerResponseOutput> {
        const response = await this.getCustomerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List customers for the merchant business (cursor pagination, archived excluded).
     */
    async listCustomersRaw(requestParameters: ListCustomersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerPageResponseOutput>> {
        const queryParameters: any = {};

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['createdFrom'] != null) {
            queryParameters['created[from]'] = requestParameters['createdFrom'];
        }

        if (requestParameters['createdTo'] != null) {
            queryParameters['created[to]'] = requestParameters['createdTo'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/customers`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerPageResponseOutputFromJSON(jsonValue));
    }

    /**
     * List customers for the merchant business (cursor pagination, archived excluded).
     */
    async listCustomers(requestParameters: ListCustomersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerPageResponseOutput> {
        const response = await this.listCustomersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update mutable fields on a customer. Idempotency-Key required on retries.
     */
    async updateCustomerRaw(requestParameters: UpdateCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CustomerResponseOutput>> {
        if (requestParameters['customerId'] == null) {
            throw new runtime.RequiredError(
                'customerId',
                'Required parameter "customerId" was null or undefined when calling updateCustomer().'
            );
        }

        if (requestParameters['updateCustomer'] == null) {
            throw new runtime.RequiredError(
                'updateCustomer',
                'Required parameter "updateCustomer" was null or undefined when calling updateCustomer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/customers/{customerId}`;
        urlPath = urlPath.replace(`{${"customerId"}}`, encodeURIComponent(String(requestParameters['customerId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateCustomerToJSON(requestParameters['updateCustomer']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomerResponseOutputFromJSON(jsonValue));
    }

    /**
     * Update mutable fields on a customer. Idempotency-Key required on retries.
     */
    async updateCustomer(requestParameters: UpdateCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CustomerResponseOutput> {
        const response = await this.updateCustomerRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
