/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateInvoice,
  InvoiceEventResponseDtoOutput,
  InvoiceMutationResponseOutput,
  InvoicePageResponseOutput,
  InvoiceResponseOutput,
  SendInvoiceResponseOutput,
  UpdateInvoice,
} from '../models/index';
import {
    CreateInvoiceFromJSON,
    CreateInvoiceToJSON,
    InvoiceEventResponseDtoOutputFromJSON,
    InvoiceEventResponseDtoOutputToJSON,
    InvoiceMutationResponseOutputFromJSON,
    InvoiceMutationResponseOutputToJSON,
    InvoicePageResponseOutputFromJSON,
    InvoicePageResponseOutputToJSON,
    InvoiceResponseOutputFromJSON,
    InvoiceResponseOutputToJSON,
    SendInvoiceResponseOutputFromJSON,
    SendInvoiceResponseOutputToJSON,
    UpdateInvoiceFromJSON,
    UpdateInvoiceToJSON,
} from '../models/index';

export interface CreateInvoiceRequest {
    createInvoice: CreateInvoice;
    idempotencyKey?: string;
}

export interface GetInvoiceRequest {
    id: string;
    idempotencyKey?: string;
}

export interface ListInvoiceEventsRequest {
    id: string;
    idempotencyKey?: string;
}

export interface ListInvoicesRequest {
    status?: string;
    limit?: string;
    cursor?: string;
    idempotencyKey?: string;
}

export interface SendInvoiceRequest {
    id: string;
    idempotencyKey?: string;
}

export interface UpdateInvoiceRequest {
    id: string;
    updateInvoice: UpdateInvoice;
    idempotencyKey?: string;
}

/**
 * 
 */
export class InvoicesApi extends runtime.BaseAPI {

    /**
     * Create a subscription-scoped invoice in draft status. Idempotency-Key required on retries.
     */
    async createInvoiceRaw(requestParameters: CreateInvoiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InvoiceMutationResponseOutput>> {
        if (requestParameters['createInvoice'] == null) {
            throw new runtime.RequiredError(
                'createInvoice',
                'Required parameter "createInvoice" was null or undefined when calling createInvoice().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/invoices`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateInvoiceToJSON(requestParameters['createInvoice']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InvoiceMutationResponseOutputFromJSON(jsonValue));
    }

    /**
     * Create a subscription-scoped invoice in draft status. Idempotency-Key required on retries.
     */
    async createInvoice(requestParameters: CreateInvoiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InvoiceMutationResponseOutput> {
        const response = await this.createInvoiceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a single invoice by ID.
     */
    async getInvoiceRaw(requestParameters: GetInvoiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InvoiceResponseOutput>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getInvoice().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/invoices/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InvoiceResponseOutputFromJSON(jsonValue));
    }

    /**
     * Get a single invoice by ID.
     */
    async getInvoice(requestParameters: GetInvoiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InvoiceResponseOutput> {
        const response = await this.getInvoiceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List the invoice event timeline (bare array, ascending). FE-vocabulary invoice.* events only.
     */
    async listInvoiceEventsRaw(requestParameters: ListInvoiceEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<InvoiceEventResponseDtoOutput>>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listInvoiceEvents().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/invoices/{id}/events`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InvoiceEventResponseDtoOutputFromJSON));
    }

    /**
     * List the invoice event timeline (bare array, ascending). FE-vocabulary invoice.* events only.
     */
    async listInvoiceEvents(requestParameters: ListInvoiceEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<InvoiceEventResponseDtoOutput>> {
        const response = await this.listInvoiceEventsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List invoices for the merchant business. Cursor pagination. Optional ?status= filter (open|paid|void|uncollectible).
     */
    async listInvoicesRaw(requestParameters: ListInvoicesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InvoicePageResponseOutput>> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/invoices`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InvoicePageResponseOutputFromJSON(jsonValue));
    }

    /**
     * List invoices for the merchant business. Cursor pagination. Optional ?status= filter (open|paid|void|uncollectible).
     */
    async listInvoices(requestParameters: ListInvoicesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InvoicePageResponseOutput> {
        const response = await this.listInvoicesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Finalize a draft invoice (draft→open). Returns the persisted invoice and the resolved customer email (sent_to_email) when reachable.
     */
    async sendInvoiceRaw(requestParameters: SendInvoiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SendInvoiceResponseOutput>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling sendInvoice().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/invoices/{id}/send`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SendInvoiceResponseOutputFromJSON(jsonValue));
    }

    /**
     * Finalize a draft invoice (draft→open). Returns the persisted invoice and the resolved customer email (sent_to_email) when reachable.
     */
    async sendInvoice(requestParameters: SendInvoiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SendInvoiceResponseOutput> {
        const response = await this.sendInvoiceRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an invoice status. body { status: \"void\" } voids an open invoice; body { status: \"paid\" } marks an open invoice paid. Non-open is rejected 4xx.
     */
    async updateInvoiceRaw(requestParameters: UpdateInvoiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InvoiceMutationResponseOutput>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateInvoice().'
            );
        }

        if (requestParameters['updateInvoice'] == null) {
            throw new runtime.RequiredError(
                'updateInvoice',
                'Required parameter "updateInvoice" was null or undefined when calling updateInvoice().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/invoices/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateInvoiceToJSON(requestParameters['updateInvoice']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InvoiceMutationResponseOutputFromJSON(jsonValue));
    }

    /**
     * Update an invoice status. body { status: \"void\" } voids an open invoice; body { status: \"paid\" } marks an open invoice paid. Non-open is rejected 4xx.
     */
    async updateInvoice(requestParameters: UpdateInvoiceRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InvoiceMutationResponseOutput> {
        const response = await this.updateInvoiceRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
