/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CancelSubscription,
  CreateSubscription,
  CreateSubscription201Response,
  ListSubscriptions200Response,
  UpdateSubscription,
} from '../models/index';
import {
    CancelSubscriptionFromJSON,
    CancelSubscriptionToJSON,
    CreateSubscriptionFromJSON,
    CreateSubscriptionToJSON,
    CreateSubscription201ResponseFromJSON,
    CreateSubscription201ResponseToJSON,
    ListSubscriptions200ResponseFromJSON,
    ListSubscriptions200ResponseToJSON,
    UpdateSubscriptionFromJSON,
    UpdateSubscriptionToJSON,
} from '../models/index';

export interface CancelSubscriptionRequest {
    id: string;
    cancelSubscription: CancelSubscription;
    idempotencyKey?: string;
}

export interface CreateSubscriptionRequest {
    createSubscription: CreateSubscription;
    idempotencyKey?: string;
}

export interface GetSubscriptionRequest {
    id: string;
    idempotencyKey?: string;
}

export interface ListSubscriptionsRequest {
    status?: string;
    limit?: string;
    cursor?: string;
    idempotencyKey?: string;
}

export interface UpdateSubscriptionRequest {
    id: string;
    updateSubscription: UpdateSubscription;
    idempotencyKey?: string;
}

/**
 * 
 */
export class SubscriptionsApi extends runtime.BaseAPI {

    /**
     * Cancel a subscription. Default (cancelAtPeriodEnd=false) is immediate. Set cancelAtPeriodEnd=true to cancel at period end.
     */
    async cancelSubscriptionRaw(requestParameters: CancelSubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateSubscription201Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling cancelSubscription().'
            );
        }

        if (requestParameters['cancelSubscription'] == null) {
            throw new runtime.RequiredError(
                'cancelSubscription',
                'Required parameter "cancelSubscription" was null or undefined when calling cancelSubscription().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/subscriptions/{id}/cancel`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CancelSubscriptionToJSON(requestParameters['cancelSubscription']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateSubscription201ResponseFromJSON(jsonValue));
    }

    /**
     * Cancel a subscription. Default (cancelAtPeriodEnd=false) is immediate. Set cancelAtPeriodEnd=true to cancel at period end.
     */
    async cancelSubscription(requestParameters: CancelSubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateSubscription201Response> {
        const response = await this.cancelSubscriptionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a subscription for a customer. Idempotency-Key required on retries. Charge is immediate unless price has a trial and skipTrial=false.
     */
    async createSubscriptionRaw(requestParameters: CreateSubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateSubscription201Response>> {
        if (requestParameters['createSubscription'] == null) {
            throw new runtime.RequiredError(
                'createSubscription',
                'Required parameter "createSubscription" was null or undefined when calling createSubscription().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/subscriptions`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateSubscriptionToJSON(requestParameters['createSubscription']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateSubscription201ResponseFromJSON(jsonValue));
    }

    /**
     * Create a subscription for a customer. Idempotency-Key required on retries. Charge is immediate unless price has a trial and skipTrial=false.
     */
    async createSubscription(requestParameters: CreateSubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateSubscription201Response> {
        const response = await this.createSubscriptionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a single subscription by ID.
     */
    async getSubscriptionRaw(requestParameters: GetSubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateSubscription201Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getSubscription().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/subscriptions/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateSubscription201ResponseFromJSON(jsonValue));
    }

    /**
     * Get a single subscription by ID.
     */
    async getSubscription(requestParameters: GetSubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateSubscription201Response> {
        const response = await this.getSubscriptionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List subscriptions for the merchant business. Cursor pagination. Optional ?status= filter (trialing|active|past_due|unpaid|cancelled).
     */
    async listSubscriptionsRaw(requestParameters: ListSubscriptionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListSubscriptions200Response>> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/subscriptions`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListSubscriptions200ResponseFromJSON(jsonValue));
    }

    /**
     * List subscriptions for the merchant business. Cursor pagination. Optional ?status= filter (trialing|active|past_due|unpaid|cancelled).
     */
    async listSubscriptions(requestParameters: ListSubscriptionsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListSubscriptions200Response> {
        const response = await this.listSubscriptionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update mutable fields on a subscription: metadata (partial merge) and cancelAtPeriodEnd (one-way, can only be set to true).
     */
    async updateSubscriptionRaw(requestParameters: UpdateSubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateSubscription201Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateSubscription().'
            );
        }

        if (requestParameters['updateSubscription'] == null) {
            throw new runtime.RequiredError(
                'updateSubscription',
                'Required parameter "updateSubscription" was null or undefined when calling updateSubscription().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/subscriptions/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateSubscriptionToJSON(requestParameters['updateSubscription']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateSubscription201ResponseFromJSON(jsonValue));
    }

    /**
     * Update mutable fields on a subscription: metadata (partial merge) and cancelAtPeriodEnd (one-way, can only be set to true).
     */
    async updateSubscription(requestParameters: UpdateSubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateSubscription201Response> {
        const response = await this.updateSubscriptionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
