/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateWebhookEndpoint,
  CreateWebhookEndpoint201Response,
  GetWebhookEndpoint200Response,
  ListWebhookDeliveries200Response,
  ListWebhookEndpoints200Response,
  ReplayWebhookDeliveries200Response,
  RotateWebhookSecret200Response,
  SendTestWebhook200Response,
  UpdateWebhookEndpoint,
} from '../models/index';
import {
    CreateWebhookEndpointFromJSON,
    CreateWebhookEndpointToJSON,
    CreateWebhookEndpoint201ResponseFromJSON,
    CreateWebhookEndpoint201ResponseToJSON,
    GetWebhookEndpoint200ResponseFromJSON,
    GetWebhookEndpoint200ResponseToJSON,
    ListWebhookDeliveries200ResponseFromJSON,
    ListWebhookDeliveries200ResponseToJSON,
    ListWebhookEndpoints200ResponseFromJSON,
    ListWebhookEndpoints200ResponseToJSON,
    ReplayWebhookDeliveries200ResponseFromJSON,
    ReplayWebhookDeliveries200ResponseToJSON,
    RotateWebhookSecret200ResponseFromJSON,
    RotateWebhookSecret200ResponseToJSON,
    SendTestWebhook200ResponseFromJSON,
    SendTestWebhook200ResponseToJSON,
    UpdateWebhookEndpointFromJSON,
    UpdateWebhookEndpointToJSON,
} from '../models/index';

export interface CreateWebhookEndpointRequest {
    createWebhookEndpoint: CreateWebhookEndpoint;
    idempotencyKey?: string;
}

export interface DeleteWebhookEndpointRequest {
    id: string;
    idempotencyKey?: string;
}

export interface GetWebhookEndpointRequest {
    id: string;
    idempotencyKey?: string;
}

export interface ListWebhookDeliveriesRequest {
    id: string;
    limit?: string;
    idempotencyKey?: string;
}

export interface ListWebhookEndpointsRequest {
    idempotencyKey?: string;
}

export interface ReplayWebhookDeliveriesRequest {
    id: string;
    idempotencyKey?: string;
}

export interface RotateWebhookSecretRequest {
    id: string;
    idempotencyKey?: string;
}

export interface SendTestWebhookRequest {
    id: string;
    idempotencyKey?: string;
}

export interface UpdateWebhookEndpointRequest {
    id: string;
    updateWebhookEndpoint: UpdateWebhookEndpoint;
    idempotencyKey?: string;
}

/**
 * 
 */
export class WebhooksApi extends runtime.BaseAPI {

    /**
     * Register a new webhook endpoint for the merchant business. Returns the generated signing secret — shown only once and must be stored securely.
     */
    async createWebhookEndpointRaw(requestParameters: CreateWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateWebhookEndpoint201Response>> {
        if (requestParameters['createWebhookEndpoint'] == null) {
            throw new runtime.RequiredError(
                'createWebhookEndpoint',
                'Required parameter "createWebhookEndpoint" was null or undefined when calling createWebhookEndpoint().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/webhooks/endpoints`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateWebhookEndpointToJSON(requestParameters['createWebhookEndpoint']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateWebhookEndpoint201ResponseFromJSON(jsonValue));
    }

    /**
     * Register a new webhook endpoint for the merchant business. Returns the generated signing secret — shown only once and must be stored securely.
     */
    async createWebhookEndpoint(requestParameters: CreateWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateWebhookEndpoint201Response> {
        const response = await this.createWebhookEndpointRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a webhook endpoint and all its outbox entries.
     */
    async deleteWebhookEndpointRaw(requestParameters: DeleteWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteWebhookEndpoint().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/webhooks/endpoints/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a webhook endpoint and all its outbox entries.
     */
    async deleteWebhookEndpoint(requestParameters: DeleteWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteWebhookEndpointRaw(requestParameters, initOverrides);
    }

    /**
     * Get a single webhook endpoint by ID. Secret is excluded.
     */
    async getWebhookEndpointRaw(requestParameters: GetWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetWebhookEndpoint200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getWebhookEndpoint().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/webhooks/endpoints/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetWebhookEndpoint200ResponseFromJSON(jsonValue));
    }

    /**
     * Get a single webhook endpoint by ID. Secret is excluded.
     */
    async getWebhookEndpoint(requestParameters: GetWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetWebhookEndpoint200Response> {
        const response = await this.getWebhookEndpointRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List the most-recent deliveries for a webhook endpoint, each with its per-attempt history and a derived status. Read-only projection of the outbox + delivery-attempts tables. Default limit 30. Returns a BARE ARRAY (NOT a { items, nextCursor } cursor page) — the FE deliveries timeline consumes ReadonlyArray<WebhookDelivery>; deliberate divergence from the list-envelope convention.
     */
    async listWebhookDeliveriesRaw(requestParameters: ListWebhookDeliveriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListWebhookDeliveries200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listWebhookDeliveries().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/webhooks/endpoints/{id}/deliveries`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListWebhookDeliveries200ResponseFromJSON(jsonValue));
    }

    /**
     * List the most-recent deliveries for a webhook endpoint, each with its per-attempt history and a derived status. Read-only projection of the outbox + delivery-attempts tables. Default limit 30. Returns a BARE ARRAY (NOT a { items, nextCursor } cursor page) — the FE deliveries timeline consumes ReadonlyArray<WebhookDelivery>; deliberate divergence from the list-envelope convention.
     */
    async listWebhookDeliveries(requestParameters: ListWebhookDeliveriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListWebhookDeliveries200Response> {
        const response = await this.listWebhookDeliveriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List webhook endpoints for the merchant business. Cursor pagination. Secret is never returned in list responses.
     */
    async listWebhookEndpointsRaw(requestParameters: ListWebhookEndpointsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListWebhookEndpoints200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/webhooks/endpoints`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListWebhookEndpoints200ResponseFromJSON(jsonValue));
    }

    /**
     * List webhook endpoints for the merchant business. Cursor pagination. Secret is never returned in list responses.
     */
    async listWebhookEndpoints(requestParameters: ListWebhookEndpointsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListWebhookEndpoints200Response> {
        const response = await this.listWebhookEndpointsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Replay all failed deliveries for this endpoint. Resets status from \"failed\" to \"pending\" and immediately retries via BullMQ. Only endpoints owned by the merchant business are affected.
     */
    async replayWebhookDeliveriesRaw(requestParameters: ReplayWebhookDeliveriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReplayWebhookDeliveries200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling replayWebhookDeliveries().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/webhooks/endpoints/{id}/replay`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReplayWebhookDeliveries200ResponseFromJSON(jsonValue));
    }

    /**
     * Replay all failed deliveries for this endpoint. Resets status from \"failed\" to \"pending\" and immediately retries via BullMQ. Only endpoints owned by the merchant business are affected.
     */
    async replayWebhookDeliveries(requestParameters: ReplayWebhookDeliveriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReplayWebhookDeliveries200Response> {
        const response = await this.replayWebhookDeliveriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Rotate the signing secret for an endpoint. Invalidates the old secret immediately and returns the new secret once. Update your webhook receiver with the new secret promptly.
     */
    async rotateWebhookSecretRaw(requestParameters: RotateWebhookSecretRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RotateWebhookSecret200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling rotateWebhookSecret().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/webhooks/endpoints/{id}/rotate-secret`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RotateWebhookSecret200ResponseFromJSON(jsonValue));
    }

    /**
     * Rotate the signing secret for an endpoint. Invalidates the old secret immediately and returns the new secret once. Update your webhook receiver with the new secret promptly.
     */
    async rotateWebhookSecret(requestParameters: RotateWebhookSecretRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RotateWebhookSecret200Response> {
        const response = await this.rotateWebhookSecretRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Send a test event to the endpoint immediately. The event is enqueued for immediate delivery via BullMQ — no scheduling delay. Use this to verify the endpoint URL, signing secret, and handler is correct.
     */
    async sendTestWebhookRaw(requestParameters: SendTestWebhookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SendTestWebhook200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling sendTestWebhook().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/webhooks/endpoints/{id}/test`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SendTestWebhook200ResponseFromJSON(jsonValue));
    }

    /**
     * Send a test event to the endpoint immediately. The event is enqueued for immediate delivery via BullMQ — no scheduling delay. Use this to verify the endpoint URL, signing secret, and handler is correct.
     */
    async sendTestWebhook(requestParameters: SendTestWebhookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SendTestWebhook200Response> {
        const response = await this.sendTestWebhookRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update mutable fields on a webhook endpoint: url, enabled_events, active, metadata.
     */
    async updateWebhookEndpointRaw(requestParameters: UpdateWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetWebhookEndpoint200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateWebhookEndpoint().'
            );
        }

        if (requestParameters['updateWebhookEndpoint'] == null) {
            throw new runtime.RequiredError(
                'updateWebhookEndpoint',
                'Required parameter "updateWebhookEndpoint" was null or undefined when calling updateWebhookEndpoint().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['idempotencyKey'] != null) {
            headerParameters['Idempotency-Key'] = String(requestParameters['idempotencyKey']);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["x-api-key"] = await this.configuration.apiKey("x-api-key"); // ApiKeyAuth authentication
        }


        let urlPath = `/v1/webhooks/endpoints/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateWebhookEndpointToJSON(requestParameters['updateWebhookEndpoint']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetWebhookEndpoint200ResponseFromJSON(jsonValue));
    }

    /**
     * Update mutable fields on a webhook endpoint: url, enabled_events, active, metadata.
     */
    async updateWebhookEndpoint(requestParameters: UpdateWebhookEndpointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetWebhookEndpoint200Response> {
        const response = await this.updateWebhookEndpointRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
