/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductArchiveResponseOutput } from './ProductArchiveResponseOutput';
import {
    ProductArchiveResponseOutputFromJSON,
    ProductArchiveResponseOutputFromJSONTyped,
    ProductArchiveResponseOutputToJSON,
    ProductArchiveResponseOutputToJSONTyped,
} from './ProductArchiveResponseOutput';
import type { ListEvents200ResponseMeta } from './ListEvents200ResponseMeta';
import {
    ListEvents200ResponseMetaFromJSON,
    ListEvents200ResponseMetaFromJSONTyped,
    ListEvents200ResponseMetaToJSON,
    ListEvents200ResponseMetaToJSONTyped,
} from './ListEvents200ResponseMeta';

/**
 * 
 * @export
 * @interface ArchiveProduct200Response
 */
export interface ArchiveProduct200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ArchiveProduct200Response
     */
    success: boolean;
    /**
     * 
     * @type {ProductArchiveResponseOutput}
     * @memberof ArchiveProduct200Response
     */
    data: ProductArchiveResponseOutput;
    /**
     * 
     * @type {ListEvents200ResponseMeta}
     * @memberof ArchiveProduct200Response
     */
    meta: ListEvents200ResponseMeta;
}

/**
 * Check if a given object implements the ArchiveProduct200Response interface.
 */
export function instanceOfArchiveProduct200Response(value: object): value is ArchiveProduct200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ArchiveProduct200ResponseFromJSON(json: any): ArchiveProduct200Response {
    return ArchiveProduct200ResponseFromJSONTyped(json, false);
}

export function ArchiveProduct200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArchiveProduct200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': ProductArchiveResponseOutputFromJSON(json['data']),
        'meta': ListEvents200ResponseMetaFromJSON(json['meta']),
    };
}

export function ArchiveProduct200ResponseToJSON(json: any): ArchiveProduct200Response {
    return ArchiveProduct200ResponseToJSONTyped(json, false);
}

export function ArchiveProduct200ResponseToJSONTyped(value?: ArchiveProduct200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ProductArchiveResponseOutputToJSON(value['data']),
        'meta': ListEvents200ResponseMetaToJSON(value['meta']),
    };
}

