/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListEvents200ResponseMeta } from './ListEvents200ResponseMeta';
import {
    ListEvents200ResponseMetaFromJSON,
    ListEvents200ResponseMetaFromJSONTyped,
    ListEvents200ResponseMetaToJSON,
    ListEvents200ResponseMetaToJSONTyped,
} from './ListEvents200ResponseMeta';
import type { CustomerArchiveResponseOutput } from './CustomerArchiveResponseOutput';
import {
    CustomerArchiveResponseOutputFromJSON,
    CustomerArchiveResponseOutputFromJSONTyped,
    CustomerArchiveResponseOutputToJSON,
    CustomerArchiveResponseOutputToJSONTyped,
} from './CustomerArchiveResponseOutput';

/**
 * 
 * @export
 * @interface ArchiveCustomer200Response
 */
export interface ArchiveCustomer200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ArchiveCustomer200Response
     */
    success: boolean;
    /**
     * 
     * @type {CustomerArchiveResponseOutput}
     * @memberof ArchiveCustomer200Response
     */
    data: CustomerArchiveResponseOutput;
    /**
     * 
     * @type {ListEvents200ResponseMeta}
     * @memberof ArchiveCustomer200Response
     */
    meta: ListEvents200ResponseMeta;
}

/**
 * Check if a given object implements the ArchiveCustomer200Response interface.
 */
export function instanceOfArchiveCustomer200Response(value: object): value is ArchiveCustomer200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ArchiveCustomer200ResponseFromJSON(json: any): ArchiveCustomer200Response {
    return ArchiveCustomer200ResponseFromJSONTyped(json, false);
}

export function ArchiveCustomer200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArchiveCustomer200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': CustomerArchiveResponseOutputFromJSON(json['data']),
        'meta': ListEvents200ResponseMetaFromJSON(json['meta']),
    };
}

export function ArchiveCustomer200ResponseToJSON(json: any): ArchiveCustomer200Response {
    return ArchiveCustomer200ResponseToJSONTyped(json, false);
}

export function ArchiveCustomer200ResponseToJSONTyped(value?: ArchiveCustomer200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': CustomerArchiveResponseOutputToJSON(value['data']),
        'meta': ListEvents200ResponseMetaToJSON(value['meta']),
    };
}

