/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListEvents200ResponseMeta } from './ListEvents200ResponseMeta';
import {
    ListEvents200ResponseMetaFromJSON,
    ListEvents200ResponseMetaFromJSONTyped,
    ListEvents200ResponseMetaToJSON,
    ListEvents200ResponseMetaToJSONTyped,
} from './ListEvents200ResponseMeta';
import type { PriceArchiveResponseOutput } from './PriceArchiveResponseOutput';
import {
    PriceArchiveResponseOutputFromJSON,
    PriceArchiveResponseOutputFromJSONTyped,
    PriceArchiveResponseOutputToJSON,
    PriceArchiveResponseOutputToJSONTyped,
} from './PriceArchiveResponseOutput';

/**
 * 
 * @export
 * @interface ArchivePrice200Response
 */
export interface ArchivePrice200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ArchivePrice200Response
     */
    success: boolean;
    /**
     * 
     * @type {PriceArchiveResponseOutput}
     * @memberof ArchivePrice200Response
     */
    data: PriceArchiveResponseOutput;
    /**
     * 
     * @type {ListEvents200ResponseMeta}
     * @memberof ArchivePrice200Response
     */
    meta: ListEvents200ResponseMeta;
}

/**
 * Check if a given object implements the ArchivePrice200Response interface.
 */
export function instanceOfArchivePrice200Response(value: object): value is ArchivePrice200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ArchivePrice200ResponseFromJSON(json: any): ArchivePrice200Response {
    return ArchivePrice200ResponseFromJSONTyped(json, false);
}

export function ArchivePrice200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArchivePrice200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': PriceArchiveResponseOutputFromJSON(json['data']),
        'meta': ListEvents200ResponseMetaFromJSON(json['meta']),
    };
}

export function ArchivePrice200ResponseToJSON(json: any): ArchivePrice200Response {
    return ArchivePrice200ResponseToJSONTyped(json, false);
}

export function ArchivePrice200ResponseToJSONTyped(value?: ArchivePrice200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': PriceArchiveResponseOutputToJSON(value['data']),
        'meta': ListEvents200ResponseMetaToJSON(value['meta']),
    };
}

