/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CancelSubscription
 */
export interface CancelSubscription {
    /**
     * 
     * @type {boolean}
     * @memberof CancelSubscription
     */
    cancelAtPeriodEnd?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CancelSubscription
     */
    reason?: string;
}

/**
 * Check if a given object implements the CancelSubscription interface.
 */
export function instanceOfCancelSubscription(value: object): value is CancelSubscription {
    return true;
}

export function CancelSubscriptionFromJSON(json: any): CancelSubscription {
    return CancelSubscriptionFromJSONTyped(json, false);
}

export function CancelSubscriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CancelSubscription {
    if (json == null) {
        return json;
    }
    return {
        
        'cancelAtPeriodEnd': json['cancelAtPeriodEnd'] == null ? undefined : json['cancelAtPeriodEnd'],
        'reason': json['reason'] == null ? undefined : json['reason'],
    };
}

export function CancelSubscriptionToJSON(json: any): CancelSubscription {
    return CancelSubscriptionToJSONTyped(json, false);
}

export function CancelSubscriptionToJSONTyped(value?: CancelSubscription | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cancelAtPeriodEnd': value['cancelAtPeriodEnd'],
        'reason': value['reason'],
    };
}

