/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListEvents200ResponseMeta } from './ListEvents200ResponseMeta';
import {
    ListEvents200ResponseMetaFromJSON,
    ListEvents200ResponseMetaFromJSONTyped,
    ListEvents200ResponseMetaToJSON,
    ListEvents200ResponseMetaToJSONTyped,
} from './ListEvents200ResponseMeta';
import type { SubscriptionResponseOutput } from './SubscriptionResponseOutput';
import {
    SubscriptionResponseOutputFromJSON,
    SubscriptionResponseOutputFromJSONTyped,
    SubscriptionResponseOutputToJSON,
    SubscriptionResponseOutputToJSONTyped,
} from './SubscriptionResponseOutput';

/**
 * 
 * @export
 * @interface CreateSubscription201Response
 */
export interface CreateSubscription201Response {
    /**
     * 
     * @type {boolean}
     * @memberof CreateSubscription201Response
     */
    success: boolean;
    /**
     * 
     * @type {SubscriptionResponseOutput}
     * @memberof CreateSubscription201Response
     */
    data: SubscriptionResponseOutput;
    /**
     * 
     * @type {ListEvents200ResponseMeta}
     * @memberof CreateSubscription201Response
     */
    meta: ListEvents200ResponseMeta;
}

/**
 * Check if a given object implements the CreateSubscription201Response interface.
 */
export function instanceOfCreateSubscription201Response(value: object): value is CreateSubscription201Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function CreateSubscription201ResponseFromJSON(json: any): CreateSubscription201Response {
    return CreateSubscription201ResponseFromJSONTyped(json, false);
}

export function CreateSubscription201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSubscription201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': SubscriptionResponseOutputFromJSON(json['data']),
        'meta': ListEvents200ResponseMetaFromJSON(json['meta']),
    };
}

export function CreateSubscription201ResponseToJSON(json: any): CreateSubscription201Response {
    return CreateSubscription201ResponseToJSONTyped(json, false);
}

export function CreateSubscription201ResponseToJSONTyped(value?: CreateSubscription201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': SubscriptionResponseOutputToJSON(value['data']),
        'meta': ListEvents200ResponseMetaToJSON(value['meta']),
    };
}

