/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateInvoice
 */
export interface CreateInvoice {
    /**
     * 
     * @type {string}
     * @memberof CreateInvoice
     */
    subscriptionId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateInvoice
     */
    amountPaisa: string;
    /**
     * 
     * @type {string}
     * @memberof CreateInvoice
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof CreateInvoice
     */
    priceId: string;
    /**
     * 
     * @type {Date}
     * @memberof CreateInvoice
     */
    periodStart: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreateInvoice
     */
    periodEnd: Date;
}

/**
 * Check if a given object implements the CreateInvoice interface.
 */
export function instanceOfCreateInvoice(value: object): value is CreateInvoice {
    if (!('subscriptionId' in value) || value['subscriptionId'] === undefined) return false;
    if (!('amountPaisa' in value) || value['amountPaisa'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('priceId' in value) || value['priceId'] === undefined) return false;
    if (!('periodStart' in value) || value['periodStart'] === undefined) return false;
    if (!('periodEnd' in value) || value['periodEnd'] === undefined) return false;
    return true;
}

export function CreateInvoiceFromJSON(json: any): CreateInvoice {
    return CreateInvoiceFromJSONTyped(json, false);
}

export function CreateInvoiceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateInvoice {
    if (json == null) {
        return json;
    }
    return {
        
        'subscriptionId': json['subscriptionId'],
        'amountPaisa': json['amountPaisa'],
        'description': json['description'],
        'priceId': json['priceId'],
        'periodStart': (new Date(json['periodStart'])),
        'periodEnd': (new Date(json['periodEnd'])),
    };
}

export function CreateInvoiceToJSON(json: any): CreateInvoice {
    return CreateInvoiceToJSONTyped(json, false);
}

export function CreateInvoiceToJSONTyped(value?: CreateInvoice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'subscriptionId': value['subscriptionId'],
        'amountPaisa': value['amountPaisa'],
        'description': value['description'],
        'priceId': value['priceId'],
        'periodStart': value['periodStart'].toISOString(),
        'periodEnd': value['periodEnd'].toISOString(),
    };
}

