/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateWebhookEndpointBodyDto
 */
export interface CreateWebhookEndpointBodyDto {
    /**
     * 
     * @type {string}
     * @memberof CreateWebhookEndpointBodyDto
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof CreateWebhookEndpointBodyDto
     */
    secret?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateWebhookEndpointBodyDto
     */
    enabled_events?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof CreateWebhookEndpointBodyDto
     */
    active?: boolean;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreateWebhookEndpointBodyDto
     */
    metadata?: { [key: string]: any; };
}

/**
 * Check if a given object implements the CreateWebhookEndpointBodyDto interface.
 */
export function instanceOfCreateWebhookEndpointBodyDto(value: object): value is CreateWebhookEndpointBodyDto {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function CreateWebhookEndpointBodyDtoFromJSON(json: any): CreateWebhookEndpointBodyDto {
    return CreateWebhookEndpointBodyDtoFromJSONTyped(json, false);
}

export function CreateWebhookEndpointBodyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWebhookEndpointBodyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'secret': json['secret'] == null ? undefined : json['secret'],
        'enabled_events': json['enabled_events'] == null ? undefined : json['enabled_events'],
        'active': json['active'] == null ? undefined : json['active'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function CreateWebhookEndpointBodyDtoToJSON(json: any): CreateWebhookEndpointBodyDto {
    return CreateWebhookEndpointBodyDtoToJSONTyped(json, false);
}

export function CreateWebhookEndpointBodyDtoToJSONTyped(value?: CreateWebhookEndpointBodyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'secret': value['secret'],
        'enabled_events': value['enabled_events'],
        'active': value['active'],
        'metadata': value['metadata'],
    };
}

