/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListEvents200ResponseMeta } from './ListEvents200ResponseMeta';
import {
    ListEvents200ResponseMetaFromJSON,
    ListEvents200ResponseMetaFromJSONTyped,
    ListEvents200ResponseMetaToJSON,
    ListEvents200ResponseMetaToJSONTyped,
} from './ListEvents200ResponseMeta';
import type { WebhookEndpointWithSecretResponseOutput } from './WebhookEndpointWithSecretResponseOutput';
import {
    WebhookEndpointWithSecretResponseOutputFromJSON,
    WebhookEndpointWithSecretResponseOutputFromJSONTyped,
    WebhookEndpointWithSecretResponseOutputToJSON,
    WebhookEndpointWithSecretResponseOutputToJSONTyped,
} from './WebhookEndpointWithSecretResponseOutput';

/**
 * 
 * @export
 * @interface CreateWebhookEndpoint201Response
 */
export interface CreateWebhookEndpoint201Response {
    /**
     * 
     * @type {boolean}
     * @memberof CreateWebhookEndpoint201Response
     */
    success: boolean;
    /**
     * 
     * @type {WebhookEndpointWithSecretResponseOutput}
     * @memberof CreateWebhookEndpoint201Response
     */
    data: WebhookEndpointWithSecretResponseOutput;
    /**
     * 
     * @type {ListEvents200ResponseMeta}
     * @memberof CreateWebhookEndpoint201Response
     */
    meta: ListEvents200ResponseMeta;
}

/**
 * Check if a given object implements the CreateWebhookEndpoint201Response interface.
 */
export function instanceOfCreateWebhookEndpoint201Response(value: object): value is CreateWebhookEndpoint201Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function CreateWebhookEndpoint201ResponseFromJSON(json: any): CreateWebhookEndpoint201Response {
    return CreateWebhookEndpoint201ResponseFromJSONTyped(json, false);
}

export function CreateWebhookEndpoint201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWebhookEndpoint201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': WebhookEndpointWithSecretResponseOutputFromJSON(json['data']),
        'meta': ListEvents200ResponseMetaFromJSON(json['meta']),
    };
}

export function CreateWebhookEndpoint201ResponseToJSON(json: any): CreateWebhookEndpoint201Response {
    return CreateWebhookEndpoint201ResponseToJSONTyped(json, false);
}

export function CreateWebhookEndpoint201ResponseToJSONTyped(value?: CreateWebhookEndpoint201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': WebhookEndpointWithSecretResponseOutputToJSON(value['data']),
        'meta': ListEvents200ResponseMetaToJSON(value['meta']),
    };
}

