/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InvoiceMutationResponseOutput } from './InvoiceMutationResponseOutput';
import {
    InvoiceMutationResponseOutputFromJSON,
    InvoiceMutationResponseOutputFromJSONTyped,
    InvoiceMutationResponseOutputToJSON,
    InvoiceMutationResponseOutputToJSONTyped,
} from './InvoiceMutationResponseOutput';
import type { ListEvents200ResponseMeta } from './ListEvents200ResponseMeta';
import {
    ListEvents200ResponseMetaFromJSON,
    ListEvents200ResponseMetaFromJSONTyped,
    ListEvents200ResponseMetaToJSON,
    ListEvents200ResponseMetaToJSONTyped,
} from './ListEvents200ResponseMeta';

/**
 * 
 * @export
 * @interface CreateInvoice201Response
 */
export interface CreateInvoice201Response {
    /**
     * 
     * @type {boolean}
     * @memberof CreateInvoice201Response
     */
    success: boolean;
    /**
     * 
     * @type {InvoiceMutationResponseOutput}
     * @memberof CreateInvoice201Response
     */
    data: InvoiceMutationResponseOutput;
    /**
     * 
     * @type {ListEvents200ResponseMeta}
     * @memberof CreateInvoice201Response
     */
    meta: ListEvents200ResponseMeta;
}

/**
 * Check if a given object implements the CreateInvoice201Response interface.
 */
export function instanceOfCreateInvoice201Response(value: object): value is CreateInvoice201Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function CreateInvoice201ResponseFromJSON(json: any): CreateInvoice201Response {
    return CreateInvoice201ResponseFromJSONTyped(json, false);
}

export function CreateInvoice201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateInvoice201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': InvoiceMutationResponseOutputFromJSON(json['data']),
        'meta': ListEvents200ResponseMetaFromJSON(json['meta']),
    };
}

export function CreateInvoice201ResponseToJSON(json: any): CreateInvoice201Response {
    return CreateInvoice201ResponseToJSONTyped(json, false);
}

export function CreateInvoice201ResponseToJSONTyped(value?: CreateInvoice201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': InvoiceMutationResponseOutputToJSON(value['data']),
        'meta': ListEvents200ResponseMetaToJSON(value['meta']),
    };
}

