/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CustomerResponseOutput } from './CustomerResponseOutput';
import {
    CustomerResponseOutputFromJSON,
    CustomerResponseOutputFromJSONTyped,
    CustomerResponseOutputToJSON,
    CustomerResponseOutputToJSONTyped,
} from './CustomerResponseOutput';
import type { ListEvents200ResponseMeta } from './ListEvents200ResponseMeta';
import {
    ListEvents200ResponseMetaFromJSON,
    ListEvents200ResponseMetaFromJSONTyped,
    ListEvents200ResponseMetaToJSON,
    ListEvents200ResponseMetaToJSONTyped,
} from './ListEvents200ResponseMeta';

/**
 * 
 * @export
 * @interface CreateCustomer201Response
 */
export interface CreateCustomer201Response {
    /**
     * 
     * @type {boolean}
     * @memberof CreateCustomer201Response
     */
    success: boolean;
    /**
     * 
     * @type {CustomerResponseOutput}
     * @memberof CreateCustomer201Response
     */
    data: CustomerResponseOutput;
    /**
     * 
     * @type {ListEvents200ResponseMeta}
     * @memberof CreateCustomer201Response
     */
    meta: ListEvents200ResponseMeta;
}

/**
 * Check if a given object implements the CreateCustomer201Response interface.
 */
export function instanceOfCreateCustomer201Response(value: object): value is CreateCustomer201Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function CreateCustomer201ResponseFromJSON(json: any): CreateCustomer201Response {
    return CreateCustomer201ResponseFromJSONTyped(json, false);
}

export function CreateCustomer201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCustomer201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': CustomerResponseOutputFromJSON(json['data']),
        'meta': ListEvents200ResponseMetaFromJSON(json['meta']),
    };
}

export function CreateCustomer201ResponseToJSON(json: any): CreateCustomer201Response {
    return CreateCustomer201ResponseToJSONTyped(json, false);
}

export function CreateCustomer201ResponseToJSONTyped(value?: CreateCustomer201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': CustomerResponseOutputToJSON(value['data']),
        'meta': ListEvents200ResponseMetaToJSON(value['meta']),
    };
}

