/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateWebhookEndpoint
 */
export interface CreateWebhookEndpoint {
    /**
     * 
     * @type {string}
     * @memberof CreateWebhookEndpoint
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof CreateWebhookEndpoint
     */
    secret?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateWebhookEndpoint
     */
    enabled_events?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof CreateWebhookEndpoint
     */
    active?: boolean;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreateWebhookEndpoint
     */
    metadata?: { [key: string]: any; };
}

/**
 * Check if a given object implements the CreateWebhookEndpoint interface.
 */
export function instanceOfCreateWebhookEndpoint(value: object): value is CreateWebhookEndpoint {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function CreateWebhookEndpointFromJSON(json: any): CreateWebhookEndpoint {
    return CreateWebhookEndpointFromJSONTyped(json, false);
}

export function CreateWebhookEndpointFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWebhookEndpoint {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
        'secret': json['secret'] == null ? undefined : json['secret'],
        'enabled_events': json['enabled_events'] == null ? undefined : json['enabled_events'],
        'active': json['active'] == null ? undefined : json['active'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function CreateWebhookEndpointToJSON(json: any): CreateWebhookEndpoint {
    return CreateWebhookEndpointToJSONTyped(json, false);
}

export function CreateWebhookEndpointToJSONTyped(value?: CreateWebhookEndpoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'secret': value['secret'],
        'enabled_events': value['enabled_events'],
        'active': value['active'],
        'metadata': value['metadata'],
    };
}

