/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateProduct
 */
export interface CreateProduct {
    /**
     * 
     * @type {string}
     * @memberof CreateProduct
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreateProduct
     */
    description?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreateProduct
     */
    metadata?: { [key: string]: any; };
}

/**
 * Check if a given object implements the CreateProduct interface.
 */
export function instanceOfCreateProduct(value: object): value is CreateProduct {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateProductFromJSON(json: any): CreateProduct {
    return CreateProductFromJSONTyped(json, false);
}

export function CreateProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProduct {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function CreateProductToJSON(json: any): CreateProduct {
    return CreateProductToJSONTyped(json, false);
}

export function CreateProductToJSONTyped(value?: CreateProduct | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'metadata': value['metadata'],
    };
}

