/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListEvents200ResponseMeta } from './ListEvents200ResponseMeta';
import {
    ListEvents200ResponseMetaFromJSON,
    ListEvents200ResponseMetaFromJSONTyped,
    ListEvents200ResponseMetaToJSON,
    ListEvents200ResponseMetaToJSONTyped,
} from './ListEvents200ResponseMeta';
import type { ProductResponseOutput } from './ProductResponseOutput';
import {
    ProductResponseOutputFromJSON,
    ProductResponseOutputFromJSONTyped,
    ProductResponseOutputToJSON,
    ProductResponseOutputToJSONTyped,
} from './ProductResponseOutput';

/**
 * 
 * @export
 * @interface CreateProduct201Response
 */
export interface CreateProduct201Response {
    /**
     * 
     * @type {boolean}
     * @memberof CreateProduct201Response
     */
    success: boolean;
    /**
     * 
     * @type {ProductResponseOutput}
     * @memberof CreateProduct201Response
     */
    data: ProductResponseOutput;
    /**
     * 
     * @type {ListEvents200ResponseMeta}
     * @memberof CreateProduct201Response
     */
    meta: ListEvents200ResponseMeta;
}

/**
 * Check if a given object implements the CreateProduct201Response interface.
 */
export function instanceOfCreateProduct201Response(value: object): value is CreateProduct201Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function CreateProduct201ResponseFromJSON(json: any): CreateProduct201Response {
    return CreateProduct201ResponseFromJSONTyped(json, false);
}

export function CreateProduct201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProduct201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': ProductResponseOutputFromJSON(json['data']),
        'meta': ListEvents200ResponseMetaFromJSON(json['meta']),
    };
}

export function CreateProduct201ResponseToJSON(json: any): CreateProduct201Response {
    return CreateProduct201ResponseToJSONTyped(json, false);
}

export function CreateProduct201ResponseToJSONTyped(value?: CreateProduct201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ProductResponseOutputToJSON(value['data']),
        'meta': ListEvents200ResponseMetaToJSON(value['meta']),
    };
}

