/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListEvents200ResponseMeta } from './ListEvents200ResponseMeta';
import {
    ListEvents200ResponseMetaFromJSON,
    ListEvents200ResponseMetaFromJSONTyped,
    ListEvents200ResponseMetaToJSON,
    ListEvents200ResponseMetaToJSONTyped,
} from './ListEvents200ResponseMeta';
import type { PriceResponseOutput } from './PriceResponseOutput';
import {
    PriceResponseOutputFromJSON,
    PriceResponseOutputFromJSONTyped,
    PriceResponseOutputToJSON,
    PriceResponseOutputToJSONTyped,
} from './PriceResponseOutput';

/**
 * 
 * @export
 * @interface CreatePrice201Response
 */
export interface CreatePrice201Response {
    /**
     * 
     * @type {boolean}
     * @memberof CreatePrice201Response
     */
    success: boolean;
    /**
     * 
     * @type {PriceResponseOutput}
     * @memberof CreatePrice201Response
     */
    data: PriceResponseOutput;
    /**
     * 
     * @type {ListEvents200ResponseMeta}
     * @memberof CreatePrice201Response
     */
    meta: ListEvents200ResponseMeta;
}

/**
 * Check if a given object implements the CreatePrice201Response interface.
 */
export function instanceOfCreatePrice201Response(value: object): value is CreatePrice201Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function CreatePrice201ResponseFromJSON(json: any): CreatePrice201Response {
    return CreatePrice201ResponseFromJSONTyped(json, false);
}

export function CreatePrice201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePrice201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': PriceResponseOutputFromJSON(json['data']),
        'meta': ListEvents200ResponseMetaFromJSON(json['meta']),
    };
}

export function CreatePrice201ResponseToJSON(json: any): CreatePrice201Response {
    return CreatePrice201ResponseToJSONTyped(json, false);
}

export function CreatePrice201ResponseToJSONTyped(value?: CreatePrice201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': PriceResponseOutputToJSON(value['data']),
        'meta': ListEvents200ResponseMetaToJSON(value['meta']),
    };
}

