/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSession
 */
export interface CreateSession {
    /**
     * 
     * @type {string}
     * @memberof CreateSession
     */
    priceId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSession
     */
    successUrl: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSession
     */
    cancelUrl: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSession
     */
    linkId?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreateSession
     */
    metadata?: { [key: string]: any; };
}

/**
 * Check if a given object implements the CreateSession interface.
 */
export function instanceOfCreateSession(value: object): value is CreateSession {
    if (!('priceId' in value) || value['priceId'] === undefined) return false;
    if (!('successUrl' in value) || value['successUrl'] === undefined) return false;
    if (!('cancelUrl' in value) || value['cancelUrl'] === undefined) return false;
    return true;
}

export function CreateSessionFromJSON(json: any): CreateSession {
    return CreateSessionFromJSONTyped(json, false);
}

export function CreateSessionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSession {
    if (json == null) {
        return json;
    }
    return {
        
        'priceId': json['priceId'],
        'successUrl': json['successUrl'],
        'cancelUrl': json['cancelUrl'],
        'linkId': json['linkId'] == null ? undefined : json['linkId'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function CreateSessionToJSON(json: any): CreateSession {
    return CreateSessionToJSONTyped(json, false);
}

export function CreateSessionToJSONTyped(value?: CreateSession | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'priceId': value['priceId'],
        'successUrl': value['successUrl'],
        'cancelUrl': value['cancelUrl'],
        'linkId': value['linkId'],
        'metadata': value['metadata'],
    };
}

