/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListEvents200ResponseMeta } from './ListEvents200ResponseMeta';
import {
    ListEvents200ResponseMetaFromJSON,
    ListEvents200ResponseMetaFromJSONTyped,
    ListEvents200ResponseMetaToJSON,
    ListEvents200ResponseMetaToJSONTyped,
} from './ListEvents200ResponseMeta';
import type { CreateSessionResponseOutput } from './CreateSessionResponseOutput';
import {
    CreateSessionResponseOutputFromJSON,
    CreateSessionResponseOutputFromJSONTyped,
    CreateSessionResponseOutputToJSON,
    CreateSessionResponseOutputToJSONTyped,
} from './CreateSessionResponseOutput';

/**
 * 
 * @export
 * @interface CreateCheckoutSession201Response
 */
export interface CreateCheckoutSession201Response {
    /**
     * 
     * @type {boolean}
     * @memberof CreateCheckoutSession201Response
     */
    success: boolean;
    /**
     * 
     * @type {CreateSessionResponseOutput}
     * @memberof CreateCheckoutSession201Response
     */
    data: CreateSessionResponseOutput;
    /**
     * 
     * @type {ListEvents200ResponseMeta}
     * @memberof CreateCheckoutSession201Response
     */
    meta: ListEvents200ResponseMeta;
}

/**
 * Check if a given object implements the CreateCheckoutSession201Response interface.
 */
export function instanceOfCreateCheckoutSession201Response(value: object): value is CreateCheckoutSession201Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function CreateCheckoutSession201ResponseFromJSON(json: any): CreateCheckoutSession201Response {
    return CreateCheckoutSession201ResponseFromJSONTyped(json, false);
}

export function CreateCheckoutSession201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCheckoutSession201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': CreateSessionResponseOutputFromJSON(json['data']),
        'meta': ListEvents200ResponseMetaFromJSON(json['meta']),
    };
}

export function CreateCheckoutSession201ResponseToJSON(json: any): CreateCheckoutSession201Response {
    return CreateCheckoutSession201ResponseToJSONTyped(json, false);
}

export function CreateCheckoutSession201ResponseToJSONTyped(value?: CreateCheckoutSession201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': CreateSessionResponseOutputToJSON(value['data']),
        'meta': ListEvents200ResponseMetaToJSON(value['meta']),
    };
}

