/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSubscription
 */
export interface CreateSubscription {
    /**
     * 
     * @type {string}
     * @memberof CreateSubscription
     */
    priceId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSubscription
     */
    customerId: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateSubscription
     */
    skipTrial?: boolean;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreateSubscription
     */
    metadata?: { [key: string]: any; };
}

/**
 * Check if a given object implements the CreateSubscription interface.
 */
export function instanceOfCreateSubscription(value: object): value is CreateSubscription {
    if (!('priceId' in value) || value['priceId'] === undefined) return false;
    if (!('customerId' in value) || value['customerId'] === undefined) return false;
    return true;
}

export function CreateSubscriptionFromJSON(json: any): CreateSubscription {
    return CreateSubscriptionFromJSONTyped(json, false);
}

export function CreateSubscriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSubscription {
    if (json == null) {
        return json;
    }
    return {
        
        'priceId': json['priceId'],
        'customerId': json['customerId'],
        'skipTrial': json['skipTrial'] == null ? undefined : json['skipTrial'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function CreateSubscriptionToJSON(json: any): CreateSubscription {
    return CreateSubscriptionToJSONTyped(json, false);
}

export function CreateSubscriptionToJSONTyped(value?: CreateSubscription | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'priceId': value['priceId'],
        'customerId': value['customerId'],
        'skipTrial': value['skipTrial'],
        'metadata': value['metadata'],
    };
}

