/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSessionResponseOutput
 */
export interface CreateSessionResponseOutput {
    /**
     * 
     * @type {string}
     * @memberof CreateSessionResponseOutput
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSessionResponseOutput
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSessionResponseOutput
     */
    environment: CreateSessionResponseOutputEnvironmentEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateSessionResponseOutput
     */
    priceId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSessionResponseOutput
     */
    linkId: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateSessionResponseOutput
     */
    successUrl: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSessionResponseOutput
     */
    cancelUrl: string;
    /**
     * 
     * @type {Date}
     * @memberof CreateSessionResponseOutput
     */
    expiresAt: Date;
    /**
     * 
     * @type {string}
     * @memberof CreateSessionResponseOutput
     */
    publicUrl: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSessionResponseOutput
     */
    publicToken: string;
    /**
     * 
     * @type {Date}
     * @memberof CreateSessionResponseOutput
     */
    createdAt: Date;
}


/**
 * @export
 */
export const CreateSessionResponseOutputEnvironmentEnum = {
    sandbox: 'sandbox',
    live: 'live'
} as const;
export type CreateSessionResponseOutputEnvironmentEnum = typeof CreateSessionResponseOutputEnvironmentEnum[keyof typeof CreateSessionResponseOutputEnvironmentEnum];


/**
 * Check if a given object implements the CreateSessionResponseOutput interface.
 */
export function instanceOfCreateSessionResponseOutput(value: object): value is CreateSessionResponseOutput {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('environment' in value) || value['environment'] === undefined) return false;
    if (!('priceId' in value) || value['priceId'] === undefined) return false;
    if (!('linkId' in value) || value['linkId'] === undefined) return false;
    if (!('successUrl' in value) || value['successUrl'] === undefined) return false;
    if (!('cancelUrl' in value) || value['cancelUrl'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    if (!('publicUrl' in value) || value['publicUrl'] === undefined) return false;
    if (!('publicToken' in value) || value['publicToken'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function CreateSessionResponseOutputFromJSON(json: any): CreateSessionResponseOutput {
    return CreateSessionResponseOutputFromJSONTyped(json, false);
}

export function CreateSessionResponseOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSessionResponseOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': json['status'],
        'environment': json['environment'],
        'priceId': json['priceId'],
        'linkId': json['linkId'],
        'successUrl': json['successUrl'],
        'cancelUrl': json['cancelUrl'],
        'expiresAt': (new Date(json['expiresAt'])),
        'publicUrl': json['publicUrl'],
        'publicToken': json['publicToken'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function CreateSessionResponseOutputToJSON(json: any): CreateSessionResponseOutput {
    return CreateSessionResponseOutputToJSONTyped(json, false);
}

export function CreateSessionResponseOutputToJSONTyped(value?: CreateSessionResponseOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': value['status'],
        'environment': value['environment'],
        'priceId': value['priceId'],
        'linkId': value['linkId'],
        'successUrl': value['successUrl'],
        'cancelUrl': value['cancelUrl'],
        'expiresAt': value['expiresAt'].toISOString(),
        'publicUrl': value['publicUrl'],
        'publicToken': value['publicToken'],
        'createdAt': value['createdAt'].toISOString(),
    };
}

