/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCustomer
 */
export interface CreateCustomer {
    /**
     * 
     * @type {string}
     * @memberof CreateCustomer
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCustomer
     */
    name?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreateCustomer
     */
    metadata?: { [key: string]: any; };
}

/**
 * Check if a given object implements the CreateCustomer interface.
 */
export function instanceOfCreateCustomer(value: object): value is CreateCustomer {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function CreateCustomerFromJSON(json: any): CreateCustomer {
    return CreateCustomerFromJSONTyped(json, false);
}

export function CreateCustomerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCustomer {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'name': json['name'] == null ? undefined : json['name'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function CreateCustomerToJSON(json: any): CreateCustomer {
    return CreateCustomerToJSONTyped(json, false);
}

export function CreateCustomerToJSONTyped(value?: CreateCustomer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'name': value['name'],
        'metadata': value['metadata'],
    };
}

