/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSubscriptionRequest
 */
export interface CreateSubscriptionRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateSubscriptionRequest
     */
    priceId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSubscriptionRequest
     */
    customerId: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateSubscriptionRequest
     */
    skipTrial?: boolean;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreateSubscriptionRequest
     */
    metadata?: { [key: string]: any; };
}

/**
 * Check if a given object implements the CreateSubscriptionRequest interface.
 */
export function instanceOfCreateSubscriptionRequest(value: object): value is CreateSubscriptionRequest {
    if (!('priceId' in value) || value['priceId'] === undefined) return false;
    if (!('customerId' in value) || value['customerId'] === undefined) return false;
    return true;
}

export function CreateSubscriptionRequestFromJSON(json: any): CreateSubscriptionRequest {
    return CreateSubscriptionRequestFromJSONTyped(json, false);
}

export function CreateSubscriptionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSubscriptionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'priceId': json['priceId'],
        'customerId': json['customerId'],
        'skipTrial': json['skipTrial'] == null ? undefined : json['skipTrial'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function CreateSubscriptionRequestToJSON(json: any): CreateSubscriptionRequest {
    return CreateSubscriptionRequestToJSONTyped(json, false);
}

export function CreateSubscriptionRequestToJSONTyped(value?: CreateSubscriptionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'priceId': value['priceId'],
        'customerId': value['customerId'],
        'skipTrial': value['skipTrial'],
        'metadata': value['metadata'],
    };
}

