/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreatePrice
 */
export interface CreatePrice {
    /**
     * 
     * @type {string}
     * @memberof CreatePrice
     */
    productId: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePrice
     */
    nickname?: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePrice
     */
    amountPaisa: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePrice
     */
    currency?: CreatePriceCurrencyEnum;
    /**
     * 
     * @type {string}
     * @memberof CreatePrice
     */
    interval: CreatePriceIntervalEnum;
    /**
     * 
     * @type {number}
     * @memberof CreatePrice
     */
    intervalCount?: number;
    /**
     * 
     * @type {number}
     * @memberof CreatePrice
     */
    trialDays?: number;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreatePrice
     */
    metadata?: { [key: string]: any; };
}


/**
 * @export
 */
export const CreatePriceCurrencyEnum = {
    npr: 'npr'
} as const;
export type CreatePriceCurrencyEnum = typeof CreatePriceCurrencyEnum[keyof typeof CreatePriceCurrencyEnum];

/**
 * @export
 */
export const CreatePriceIntervalEnum = {
    day: 'day',
    week: 'week',
    month: 'month',
    year: 'year'
} as const;
export type CreatePriceIntervalEnum = typeof CreatePriceIntervalEnum[keyof typeof CreatePriceIntervalEnum];


/**
 * Check if a given object implements the CreatePrice interface.
 */
export function instanceOfCreatePrice(value: object): value is CreatePrice {
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('amountPaisa' in value) || value['amountPaisa'] === undefined) return false;
    if (!('interval' in value) || value['interval'] === undefined) return false;
    return true;
}

export function CreatePriceFromJSON(json: any): CreatePrice {
    return CreatePriceFromJSONTyped(json, false);
}

export function CreatePriceFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePrice {
    if (json == null) {
        return json;
    }
    return {
        
        'productId': json['productId'],
        'nickname': json['nickname'] == null ? undefined : json['nickname'],
        'amountPaisa': json['amountPaisa'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'interval': json['interval'],
        'intervalCount': json['intervalCount'] == null ? undefined : json['intervalCount'],
        'trialDays': json['trialDays'] == null ? undefined : json['trialDays'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function CreatePriceToJSON(json: any): CreatePrice {
    return CreatePriceToJSONTyped(json, false);
}

export function CreatePriceToJSONTyped(value?: CreatePrice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'productId': value['productId'],
        'nickname': value['nickname'],
        'amountPaisa': value['amountPaisa'],
        'currency': value['currency'],
        'interval': value['interval'],
        'intervalCount': value['intervalCount'],
        'trialDays': value['trialDays'],
        'metadata': value['metadata'],
    };
}

