/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CustomerResponseOutput } from './CustomerResponseOutput';
import {
    CustomerResponseOutputFromJSON,
    CustomerResponseOutputFromJSONTyped,
    CustomerResponseOutputToJSON,
    CustomerResponseOutputToJSONTyped,
} from './CustomerResponseOutput';

/**
 * 
 * @export
 * @interface CustomerPageResponseOutput
 */
export interface CustomerPageResponseOutput {
    /**
     * 
     * @type {Array<CustomerResponseOutput>}
     * @memberof CustomerPageResponseOutput
     */
    items: Array<CustomerResponseOutput>;
    /**
     * 
     * @type {string}
     * @memberof CustomerPageResponseOutput
     */
    nextCursor: string | null;
}

/**
 * Check if a given object implements the CustomerPageResponseOutput interface.
 */
export function instanceOfCustomerPageResponseOutput(value: object): value is CustomerPageResponseOutput {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
    return true;
}

export function CustomerPageResponseOutputFromJSON(json: any): CustomerPageResponseOutput {
    return CustomerPageResponseOutputFromJSONTyped(json, false);
}

export function CustomerPageResponseOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerPageResponseOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(CustomerResponseOutputFromJSON)),
        'nextCursor': json['nextCursor'],
    };
}

export function CustomerPageResponseOutputToJSON(json: any): CustomerPageResponseOutput {
    return CustomerPageResponseOutputToJSONTyped(json, false);
}

export function CustomerPageResponseOutputToJSONTyped(value?: CustomerPageResponseOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(CustomerResponseOutputToJSON)),
        'nextCursor': value['nextCursor'],
    };
}

