/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomerArchiveResponseOutput
 */
export interface CustomerArchiveResponseOutput {
    /**
     * 
     * @type {boolean}
     * @memberof CustomerArchiveResponseOutput
     */
    archived: boolean;
    /**
     * 
     * @type {string}
     * @memberof CustomerArchiveResponseOutput
     */
    customerId: string;
}

/**
 * Check if a given object implements the CustomerArchiveResponseOutput interface.
 */
export function instanceOfCustomerArchiveResponseOutput(value: object): value is CustomerArchiveResponseOutput {
    if (!('archived' in value) || value['archived'] === undefined) return false;
    if (!('customerId' in value) || value['customerId'] === undefined) return false;
    return true;
}

export function CustomerArchiveResponseOutputFromJSON(json: any): CustomerArchiveResponseOutput {
    return CustomerArchiveResponseOutputFromJSONTyped(json, false);
}

export function CustomerArchiveResponseOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerArchiveResponseOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'archived': json['archived'],
        'customerId': json['customerId'],
    };
}

export function CustomerArchiveResponseOutputToJSON(json: any): CustomerArchiveResponseOutput {
    return CustomerArchiveResponseOutputToJSONTyped(json, false);
}

export function CustomerArchiveResponseOutputToJSONTyped(value?: CustomerArchiveResponseOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'archived': value['archived'],
        'customerId': value['customerId'],
    };
}

