/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CustomerResponseOutput
 */
export interface CustomerResponseOutput {
    /**
     * 
     * @type {string}
     * @memberof CustomerResponseOutput
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerResponseOutput
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerResponseOutput
     */
    name: string | null;
    /**
     * 
     * @type {any}
     * @memberof CustomerResponseOutput
     */
    metadata: any | null;
    /**
     * 
     * @type {number}
     * @memberof CustomerResponseOutput
     */
    activeSubscriptionsCount: number;
    /**
     * 
     * @type {string}
     * @memberof CustomerResponseOutput
     */
    lifetimeValueMinor: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerResponseOutput
     */
    status: CustomerResponseOutputStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof CustomerResponseOutput
     */
    createdAt: Date;
}


/**
 * @export
 */
export const CustomerResponseOutputStatusEnum = {
    active: 'active',
    canceled: 'canceled',
    none: 'none'
} as const;
export type CustomerResponseOutputStatusEnum = typeof CustomerResponseOutputStatusEnum[keyof typeof CustomerResponseOutputStatusEnum];


/**
 * Check if a given object implements the CustomerResponseOutput interface.
 */
export function instanceOfCustomerResponseOutput(value: object): value is CustomerResponseOutput {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('activeSubscriptionsCount' in value) || value['activeSubscriptionsCount'] === undefined) return false;
    if (!('lifetimeValueMinor' in value) || value['lifetimeValueMinor'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function CustomerResponseOutputFromJSON(json: any): CustomerResponseOutput {
    return CustomerResponseOutputFromJSONTyped(json, false);
}

export function CustomerResponseOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomerResponseOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'email': json['email'],
        'name': json['name'],
        'metadata': json['metadata'],
        'activeSubscriptionsCount': json['activeSubscriptionsCount'],
        'lifetimeValueMinor': json['lifetimeValueMinor'],
        'status': json['status'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function CustomerResponseOutputToJSON(json: any): CustomerResponseOutput {
    return CustomerResponseOutputToJSONTyped(json, false);
}

export function CustomerResponseOutputToJSONTyped(value?: CustomerResponseOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': value['email'],
        'name': value['name'],
        'metadata': value['metadata'],
        'activeSubscriptionsCount': value['activeSubscriptionsCount'],
        'lifetimeValueMinor': value['lifetimeValueMinor'],
        'status': value['status'],
        'createdAt': value['createdAt'].toISOString(),
    };
}

