/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EventResponseOutput
 */
export interface EventResponseOutput {
    /**
     * 
     * @type {string}
     * @memberof EventResponseOutput
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof EventResponseOutput
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof EventResponseOutput
     */
    category: EventResponseOutputCategoryEnum;
    /**
     * 
     * @type {string}
     * @memberof EventResponseOutput
     */
    resourceType: string;
    /**
     * 
     * @type {string}
     * @memberof EventResponseOutput
     */
    resourceId: string;
    /**
     * 
     * @type {any}
     * @memberof EventResponseOutput
     */
    payload: any | null;
    /**
     * 
     * @type {string}
     * @memberof EventResponseOutput
     */
    apiVersion: string;
    /**
     * 
     * @type {string}
     * @memberof EventResponseOutput
     */
    idempotencyKey?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof EventResponseOutput
     */
    createdAt: Date;
}


/**
 * @export
 */
export const EventResponseOutputCategoryEnum = {
    payment: 'payment',
    subscription: 'subscription',
    customer: 'customer'
} as const;
export type EventResponseOutputCategoryEnum = typeof EventResponseOutputCategoryEnum[keyof typeof EventResponseOutputCategoryEnum];


/**
 * Check if a given object implements the EventResponseOutput interface.
 */
export function instanceOfEventResponseOutput(value: object): value is EventResponseOutput {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('resourceType' in value) || value['resourceType'] === undefined) return false;
    if (!('resourceId' in value) || value['resourceId'] === undefined) return false;
    if (!('payload' in value) || value['payload'] === undefined) return false;
    if (!('apiVersion' in value) || value['apiVersion'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function EventResponseOutputFromJSON(json: any): EventResponseOutput {
    return EventResponseOutputFromJSONTyped(json, false);
}

export function EventResponseOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventResponseOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'category': json['category'],
        'resourceType': json['resourceType'],
        'resourceId': json['resourceId'],
        'payload': json['payload'],
        'apiVersion': json['apiVersion'],
        'idempotencyKey': json['idempotencyKey'] == null ? undefined : json['idempotencyKey'],
        'createdAt': (new Date(json['createdAt'])),
    };
}

export function EventResponseOutputToJSON(json: any): EventResponseOutput {
    return EventResponseOutputToJSONTyped(json, false);
}

export function EventResponseOutputToJSONTyped(value?: EventResponseOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'category': value['category'],
        'resourceType': value['resourceType'],
        'resourceId': value['resourceId'],
        'payload': value['payload'],
        'apiVersion': value['apiVersion'],
        'idempotencyKey': value['idempotencyKey'],
        'createdAt': value['createdAt'].toISOString(),
    };
}

