/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EventResponseOutput } from './EventResponseOutput';
import {
    EventResponseOutputFromJSON,
    EventResponseOutputFromJSONTyped,
    EventResponseOutputToJSON,
    EventResponseOutputToJSONTyped,
} from './EventResponseOutput';

/**
 * 
 * @export
 * @interface EventPageResponseOutput
 */
export interface EventPageResponseOutput {
    /**
     * 
     * @type {Array<EventResponseOutput>}
     * @memberof EventPageResponseOutput
     */
    items: Array<EventResponseOutput>;
    /**
     * 
     * @type {string}
     * @memberof EventPageResponseOutput
     */
    nextCursor: string | null;
}

/**
 * Check if a given object implements the EventPageResponseOutput interface.
 */
export function instanceOfEventPageResponseOutput(value: object): value is EventPageResponseOutput {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
    return true;
}

export function EventPageResponseOutputFromJSON(json: any): EventPageResponseOutput {
    return EventPageResponseOutputFromJSONTyped(json, false);
}

export function EventPageResponseOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventPageResponseOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(EventResponseOutputFromJSON)),
        'nextCursor': json['nextCursor'],
    };
}

export function EventPageResponseOutputToJSON(json: any): EventPageResponseOutput {
    return EventPageResponseOutputToJSONTyped(json, false);
}

export function EventPageResponseOutputToJSONTyped(value?: EventPageResponseOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(EventResponseOutputToJSON)),
        'nextCursor': value['nextCursor'],
    };
}

