/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListEvents200ResponseMeta } from './ListEvents200ResponseMeta';
import {
    ListEvents200ResponseMetaFromJSON,
    ListEvents200ResponseMetaFromJSONTyped,
    ListEvents200ResponseMetaToJSON,
    ListEvents200ResponseMetaToJSONTyped,
} from './ListEvents200ResponseMeta';
import type { EventResponseOutput } from './EventResponseOutput';
import {
    EventResponseOutputFromJSON,
    EventResponseOutputFromJSONTyped,
    EventResponseOutputToJSON,
    EventResponseOutputToJSONTyped,
} from './EventResponseOutput';

/**
 * 
 * @export
 * @interface GetEvent200Response
 */
export interface GetEvent200Response {
    /**
     * 
     * @type {boolean}
     * @memberof GetEvent200Response
     */
    success: boolean;
    /**
     * 
     * @type {EventResponseOutput}
     * @memberof GetEvent200Response
     */
    data: EventResponseOutput;
    /**
     * 
     * @type {ListEvents200ResponseMeta}
     * @memberof GetEvent200Response
     */
    meta: ListEvents200ResponseMeta;
}

/**
 * Check if a given object implements the GetEvent200Response interface.
 */
export function instanceOfGetEvent200Response(value: object): value is GetEvent200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function GetEvent200ResponseFromJSON(json: any): GetEvent200Response {
    return GetEvent200ResponseFromJSONTyped(json, false);
}

export function GetEvent200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEvent200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': EventResponseOutputFromJSON(json['data']),
        'meta': ListEvents200ResponseMetaFromJSON(json['meta']),
    };
}

export function GetEvent200ResponseToJSON(json: any): GetEvent200Response {
    return GetEvent200ResponseToJSONTyped(json, false);
}

export function GetEvent200ResponseToJSONTyped(value?: GetEvent200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': EventResponseOutputToJSON(value['data']),
        'meta': ListEvents200ResponseMetaToJSON(value['meta']),
    };
}

