/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListEvents200ResponseMeta } from './ListEvents200ResponseMeta';
import {
    ListEvents200ResponseMetaFromJSON,
    ListEvents200ResponseMetaFromJSONTyped,
    ListEvents200ResponseMetaToJSON,
    ListEvents200ResponseMetaToJSONTyped,
} from './ListEvents200ResponseMeta';
import type { InvoiceResponseOutput } from './InvoiceResponseOutput';
import {
    InvoiceResponseOutputFromJSON,
    InvoiceResponseOutputFromJSONTyped,
    InvoiceResponseOutputToJSON,
    InvoiceResponseOutputToJSONTyped,
} from './InvoiceResponseOutput';

/**
 * 
 * @export
 * @interface GetInvoice200Response
 */
export interface GetInvoice200Response {
    /**
     * 
     * @type {boolean}
     * @memberof GetInvoice200Response
     */
    success: boolean;
    /**
     * 
     * @type {InvoiceResponseOutput}
     * @memberof GetInvoice200Response
     */
    data: InvoiceResponseOutput;
    /**
     * 
     * @type {ListEvents200ResponseMeta}
     * @memberof GetInvoice200Response
     */
    meta: ListEvents200ResponseMeta;
}

/**
 * Check if a given object implements the GetInvoice200Response interface.
 */
export function instanceOfGetInvoice200Response(value: object): value is GetInvoice200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function GetInvoice200ResponseFromJSON(json: any): GetInvoice200Response {
    return GetInvoice200ResponseFromJSONTyped(json, false);
}

export function GetInvoice200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetInvoice200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': InvoiceResponseOutputFromJSON(json['data']),
        'meta': ListEvents200ResponseMetaFromJSON(json['meta']),
    };
}

export function GetInvoice200ResponseToJSON(json: any): GetInvoice200Response {
    return GetInvoice200ResponseToJSONTyped(json, false);
}

export function GetInvoice200ResponseToJSONTyped(value?: GetInvoice200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': InvoiceResponseOutputToJSON(value['data']),
        'meta': ListEvents200ResponseMetaToJSON(value['meta']),
    };
}

