/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListEvents200ResponseMeta } from './ListEvents200ResponseMeta';
import {
    ListEvents200ResponseMetaFromJSON,
    ListEvents200ResponseMetaFromJSONTyped,
    ListEvents200ResponseMetaToJSON,
    ListEvents200ResponseMetaToJSONTyped,
} from './ListEvents200ResponseMeta';
import type { WebhookEndpointResponseOutput } from './WebhookEndpointResponseOutput';
import {
    WebhookEndpointResponseOutputFromJSON,
    WebhookEndpointResponseOutputFromJSONTyped,
    WebhookEndpointResponseOutputToJSON,
    WebhookEndpointResponseOutputToJSONTyped,
} from './WebhookEndpointResponseOutput';

/**
 * 
 * @export
 * @interface GetWebhookEndpoint200Response
 */
export interface GetWebhookEndpoint200Response {
    /**
     * 
     * @type {boolean}
     * @memberof GetWebhookEndpoint200Response
     */
    success: boolean;
    /**
     * 
     * @type {WebhookEndpointResponseOutput}
     * @memberof GetWebhookEndpoint200Response
     */
    data: WebhookEndpointResponseOutput;
    /**
     * 
     * @type {ListEvents200ResponseMeta}
     * @memberof GetWebhookEndpoint200Response
     */
    meta: ListEvents200ResponseMeta;
}

/**
 * Check if a given object implements the GetWebhookEndpoint200Response interface.
 */
export function instanceOfGetWebhookEndpoint200Response(value: object): value is GetWebhookEndpoint200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function GetWebhookEndpoint200ResponseFromJSON(json: any): GetWebhookEndpoint200Response {
    return GetWebhookEndpoint200ResponseFromJSONTyped(json, false);
}

export function GetWebhookEndpoint200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetWebhookEndpoint200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': WebhookEndpointResponseOutputFromJSON(json['data']),
        'meta': ListEvents200ResponseMetaFromJSON(json['meta']),
    };
}

export function GetWebhookEndpoint200ResponseToJSON(json: any): GetWebhookEndpoint200Response {
    return GetWebhookEndpoint200ResponseToJSONTyped(json, false);
}

export function GetWebhookEndpoint200ResponseToJSONTyped(value?: GetWebhookEndpoint200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': WebhookEndpointResponseOutputToJSON(value['data']),
        'meta': ListEvents200ResponseMetaToJSON(value['meta']),
    };
}

