/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvoiceResponseOutput
 */
export interface InvoiceResponseOutput {
    /**
     * 
     * @type {string}
     * @memberof InvoiceResponseOutput
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceResponseOutput
     */
    businessId: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceResponseOutput
     */
    subscriptionId: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceResponseOutput
     */
    invoiceNumber: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceResponseOutput
     */
    status: InvoiceResponseOutputStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof InvoiceResponseOutput
     */
    periodStart: Date;
    /**
     * 
     * @type {Date}
     * @memberof InvoiceResponseOutput
     */
    periodEnd: Date;
    /**
     * 
     * @type {string}
     * @memberof InvoiceResponseOutput
     */
    totalAmountPaisa: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceResponseOutput
     */
    currency: string;
    /**
     * 
     * @type {any}
     * @memberof InvoiceResponseOutput
     */
    metadata: any | null;
    /**
     * 
     * @type {Date}
     * @memberof InvoiceResponseOutput
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof InvoiceResponseOutput
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const InvoiceResponseOutputStatusEnum = {
    draft: 'draft',
    open: 'open',
    paid: 'paid',
    void: 'void',
    uncollectible: 'uncollectible'
} as const;
export type InvoiceResponseOutputStatusEnum = typeof InvoiceResponseOutputStatusEnum[keyof typeof InvoiceResponseOutputStatusEnum];


/**
 * Check if a given object implements the InvoiceResponseOutput interface.
 */
export function instanceOfInvoiceResponseOutput(value: object): value is InvoiceResponseOutput {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('businessId' in value) || value['businessId'] === undefined) return false;
    if (!('subscriptionId' in value) || value['subscriptionId'] === undefined) return false;
    if (!('invoiceNumber' in value) || value['invoiceNumber'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('periodStart' in value) || value['periodStart'] === undefined) return false;
    if (!('periodEnd' in value) || value['periodEnd'] === undefined) return false;
    if (!('totalAmountPaisa' in value) || value['totalAmountPaisa'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function InvoiceResponseOutputFromJSON(json: any): InvoiceResponseOutput {
    return InvoiceResponseOutputFromJSONTyped(json, false);
}

export function InvoiceResponseOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceResponseOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'businessId': json['businessId'],
        'subscriptionId': json['subscriptionId'],
        'invoiceNumber': json['invoiceNumber'],
        'status': json['status'],
        'periodStart': (new Date(json['periodStart'])),
        'periodEnd': (new Date(json['periodEnd'])),
        'totalAmountPaisa': json['totalAmountPaisa'],
        'currency': json['currency'],
        'metadata': json['metadata'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function InvoiceResponseOutputToJSON(json: any): InvoiceResponseOutput {
    return InvoiceResponseOutputToJSONTyped(json, false);
}

export function InvoiceResponseOutputToJSONTyped(value?: InvoiceResponseOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'businessId': value['businessId'],
        'subscriptionId': value['subscriptionId'],
        'invoiceNumber': value['invoiceNumber'],
        'status': value['status'],
        'periodStart': value['periodStart'].toISOString(),
        'periodEnd': value['periodEnd'].toISOString(),
        'totalAmountPaisa': value['totalAmountPaisa'],
        'currency': value['currency'],
        'metadata': value['metadata'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

