/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvoiceEventResponseDtoOutput
 */
export interface InvoiceEventResponseDtoOutput {
    /**
     * 
     * @type {string}
     * @memberof InvoiceEventResponseDtoOutput
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceEventResponseDtoOutput
     */
    type: InvoiceEventResponseDtoOutputTypeEnum;
    /**
     * 
     * @type {Date}
     * @memberof InvoiceEventResponseDtoOutput
     */
    occurred_at: Date;
    /**
     * 
     * @type {string}
     * @memberof InvoiceEventResponseDtoOutput
     */
    description?: string | null;
}


/**
 * @export
 */
export const InvoiceEventResponseDtoOutputTypeEnum = {
    invoice_created: 'invoice.created',
    invoice_sent: 'invoice.sent',
    invoice_opened: 'invoice.opened',
    invoice_paid_succeeded: 'invoice.paid_succeeded',
    invoice_paid_failed: 'invoice.paid_failed',
    invoice_voided: 'invoice.voided',
    invoice_uncollectible: 'invoice.uncollectible'
} as const;
export type InvoiceEventResponseDtoOutputTypeEnum = typeof InvoiceEventResponseDtoOutputTypeEnum[keyof typeof InvoiceEventResponseDtoOutputTypeEnum];


/**
 * Check if a given object implements the InvoiceEventResponseDtoOutput interface.
 */
export function instanceOfInvoiceEventResponseDtoOutput(value: object): value is InvoiceEventResponseDtoOutput {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('occurred_at' in value) || value['occurred_at'] === undefined) return false;
    return true;
}

export function InvoiceEventResponseDtoOutputFromJSON(json: any): InvoiceEventResponseDtoOutput {
    return InvoiceEventResponseDtoOutputFromJSONTyped(json, false);
}

export function InvoiceEventResponseDtoOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceEventResponseDtoOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'type': json['type'],
        'occurred_at': (new Date(json['occurred_at'])),
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function InvoiceEventResponseDtoOutputToJSON(json: any): InvoiceEventResponseDtoOutput {
    return InvoiceEventResponseDtoOutputToJSONTyped(json, false);
}

export function InvoiceEventResponseDtoOutputToJSONTyped(value?: InvoiceEventResponseDtoOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'occurred_at': value['occurred_at'].toISOString(),
        'description': value['description'],
    };
}

