/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InvoiceResponseOutput } from './InvoiceResponseOutput';
import {
    InvoiceResponseOutputFromJSON,
    InvoiceResponseOutputFromJSONTyped,
    InvoiceResponseOutputToJSON,
    InvoiceResponseOutputToJSONTyped,
} from './InvoiceResponseOutput';

/**
 * 
 * @export
 * @interface InvoicePageResponseOutput
 */
export interface InvoicePageResponseOutput {
    /**
     * 
     * @type {Array<InvoiceResponseOutput>}
     * @memberof InvoicePageResponseOutput
     */
    items: Array<InvoiceResponseOutput>;
    /**
     * 
     * @type {string}
     * @memberof InvoicePageResponseOutput
     */
    nextCursor: string | null;
}

/**
 * Check if a given object implements the InvoicePageResponseOutput interface.
 */
export function instanceOfInvoicePageResponseOutput(value: object): value is InvoicePageResponseOutput {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
    return true;
}

export function InvoicePageResponseOutputFromJSON(json: any): InvoicePageResponseOutput {
    return InvoicePageResponseOutputFromJSONTyped(json, false);
}

export function InvoicePageResponseOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoicePageResponseOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(InvoiceResponseOutputFromJSON)),
        'nextCursor': json['nextCursor'],
    };
}

export function InvoicePageResponseOutputToJSON(json: any): InvoicePageResponseOutput {
    return InvoicePageResponseOutputToJSONTyped(json, false);
}

export function InvoicePageResponseOutputToJSONTyped(value?: InvoicePageResponseOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(InvoiceResponseOutputToJSON)),
        'nextCursor': value['nextCursor'],
    };
}

