/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InvoiceResponseOutput } from './InvoiceResponseOutput';
import {
    InvoiceResponseOutputFromJSON,
    InvoiceResponseOutputFromJSONTyped,
    InvoiceResponseOutputToJSON,
    InvoiceResponseOutputToJSONTyped,
} from './InvoiceResponseOutput';

/**
 * 
 * @export
 * @interface InvoiceMutationResponseOutput
 */
export interface InvoiceMutationResponseOutput {
    /**
     * 
     * @type {InvoiceResponseOutput}
     * @memberof InvoiceMutationResponseOutput
     */
    invoice: InvoiceResponseOutput;
}

/**
 * Check if a given object implements the InvoiceMutationResponseOutput interface.
 */
export function instanceOfInvoiceMutationResponseOutput(value: object): value is InvoiceMutationResponseOutput {
    if (!('invoice' in value) || value['invoice'] === undefined) return false;
    return true;
}

export function InvoiceMutationResponseOutputFromJSON(json: any): InvoiceMutationResponseOutput {
    return InvoiceMutationResponseOutputFromJSONTyped(json, false);
}

export function InvoiceMutationResponseOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceMutationResponseOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'invoice': InvoiceResponseOutputFromJSON(json['invoice']),
    };
}

export function InvoiceMutationResponseOutputToJSON(json: any): InvoiceMutationResponseOutput {
    return InvoiceMutationResponseOutputToJSONTyped(json, false);
}

export function InvoiceMutationResponseOutputToJSONTyped(value?: InvoiceMutationResponseOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'invoice': InvoiceResponseOutputToJSON(value['invoice']),
    };
}

