/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListEvents200ResponseMeta } from './ListEvents200ResponseMeta';
import {
    ListEvents200ResponseMetaFromJSON,
    ListEvents200ResponseMetaFromJSONTyped,
    ListEvents200ResponseMetaToJSON,
    ListEvents200ResponseMetaToJSONTyped,
} from './ListEvents200ResponseMeta';
import type { CustomerPageResponseOutput } from './CustomerPageResponseOutput';
import {
    CustomerPageResponseOutputFromJSON,
    CustomerPageResponseOutputFromJSONTyped,
    CustomerPageResponseOutputToJSON,
    CustomerPageResponseOutputToJSONTyped,
} from './CustomerPageResponseOutput';

/**
 * 
 * @export
 * @interface ListCustomers200Response
 */
export interface ListCustomers200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ListCustomers200Response
     */
    success: boolean;
    /**
     * 
     * @type {CustomerPageResponseOutput}
     * @memberof ListCustomers200Response
     */
    data: CustomerPageResponseOutput;
    /**
     * 
     * @type {ListEvents200ResponseMeta}
     * @memberof ListCustomers200Response
     */
    meta: ListEvents200ResponseMeta;
}

/**
 * Check if a given object implements the ListCustomers200Response interface.
 */
export function instanceOfListCustomers200Response(value: object): value is ListCustomers200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ListCustomers200ResponseFromJSON(json: any): ListCustomers200Response {
    return ListCustomers200ResponseFromJSONTyped(json, false);
}

export function ListCustomers200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCustomers200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': CustomerPageResponseOutputFromJSON(json['data']),
        'meta': ListEvents200ResponseMetaFromJSON(json['meta']),
    };
}

export function ListCustomers200ResponseToJSON(json: any): ListCustomers200Response {
    return ListCustomers200ResponseToJSONTyped(json, false);
}

export function ListCustomers200ResponseToJSONTyped(value?: ListCustomers200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': CustomerPageResponseOutputToJSON(value['data']),
        'meta': ListEvents200ResponseMetaToJSON(value['meta']),
    };
}

