/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListEvents200ResponseMeta } from './ListEvents200ResponseMeta';
import {
    ListEvents200ResponseMetaFromJSON,
    ListEvents200ResponseMetaFromJSONTyped,
    ListEvents200ResponseMetaToJSON,
    ListEvents200ResponseMetaToJSONTyped,
} from './ListEvents200ResponseMeta';
import type { ProductPageResponseOutput } from './ProductPageResponseOutput';
import {
    ProductPageResponseOutputFromJSON,
    ProductPageResponseOutputFromJSONTyped,
    ProductPageResponseOutputToJSON,
    ProductPageResponseOutputToJSONTyped,
} from './ProductPageResponseOutput';

/**
 * 
 * @export
 * @interface ListProducts200Response
 */
export interface ListProducts200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ListProducts200Response
     */
    success: boolean;
    /**
     * 
     * @type {ProductPageResponseOutput}
     * @memberof ListProducts200Response
     */
    data: ProductPageResponseOutput;
    /**
     * 
     * @type {ListEvents200ResponseMeta}
     * @memberof ListProducts200Response
     */
    meta: ListEvents200ResponseMeta;
}

/**
 * Check if a given object implements the ListProducts200Response interface.
 */
export function instanceOfListProducts200Response(value: object): value is ListProducts200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ListProducts200ResponseFromJSON(json: any): ListProducts200Response {
    return ListProducts200ResponseFromJSONTyped(json, false);
}

export function ListProducts200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListProducts200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': ProductPageResponseOutputFromJSON(json['data']),
        'meta': ListEvents200ResponseMetaFromJSON(json['meta']),
    };
}

export function ListProducts200ResponseToJSON(json: any): ListProducts200Response {
    return ListProducts200ResponseToJSONTyped(json, false);
}

export function ListProducts200ResponseToJSONTyped(value?: ListProducts200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ProductPageResponseOutputToJSON(value['data']),
        'meta': ListEvents200ResponseMetaToJSON(value['meta']),
    };
}

