/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListEvents200ResponseMeta } from './ListEvents200ResponseMeta';
import {
    ListEvents200ResponseMetaFromJSON,
    ListEvents200ResponseMetaFromJSONTyped,
    ListEvents200ResponseMetaToJSON,
    ListEvents200ResponseMetaToJSONTyped,
} from './ListEvents200ResponseMeta';
import type { PricePageResponseOutput } from './PricePageResponseOutput';
import {
    PricePageResponseOutputFromJSON,
    PricePageResponseOutputFromJSONTyped,
    PricePageResponseOutputToJSON,
    PricePageResponseOutputToJSONTyped,
} from './PricePageResponseOutput';

/**
 * 
 * @export
 * @interface ListPrices200Response
 */
export interface ListPrices200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ListPrices200Response
     */
    success: boolean;
    /**
     * 
     * @type {PricePageResponseOutput}
     * @memberof ListPrices200Response
     */
    data: PricePageResponseOutput;
    /**
     * 
     * @type {ListEvents200ResponseMeta}
     * @memberof ListPrices200Response
     */
    meta: ListEvents200ResponseMeta;
}

/**
 * Check if a given object implements the ListPrices200Response interface.
 */
export function instanceOfListPrices200Response(value: object): value is ListPrices200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ListPrices200ResponseFromJSON(json: any): ListPrices200Response {
    return ListPrices200ResponseFromJSONTyped(json, false);
}

export function ListPrices200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListPrices200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': PricePageResponseOutputFromJSON(json['data']),
        'meta': ListEvents200ResponseMetaFromJSON(json['meta']),
    };
}

export function ListPrices200ResponseToJSON(json: any): ListPrices200Response {
    return ListPrices200ResponseToJSONTyped(json, false);
}

export function ListPrices200ResponseToJSONTyped(value?: ListPrices200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': PricePageResponseOutputToJSON(value['data']),
        'meta': ListEvents200ResponseMetaToJSON(value['meta']),
    };
}

