/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListEvents200ResponseMeta } from './ListEvents200ResponseMeta';
import {
    ListEvents200ResponseMetaFromJSON,
    ListEvents200ResponseMetaFromJSONTyped,
    ListEvents200ResponseMetaToJSON,
    ListEvents200ResponseMetaToJSONTyped,
} from './ListEvents200ResponseMeta';
import type { InvoiceEventResponseDtoOutput } from './InvoiceEventResponseDtoOutput';
import {
    InvoiceEventResponseDtoOutputFromJSON,
    InvoiceEventResponseDtoOutputFromJSONTyped,
    InvoiceEventResponseDtoOutputToJSON,
    InvoiceEventResponseDtoOutputToJSONTyped,
} from './InvoiceEventResponseDtoOutput';

/**
 * 
 * @export
 * @interface ListInvoiceEvents200Response
 */
export interface ListInvoiceEvents200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ListInvoiceEvents200Response
     */
    success: boolean;
    /**
     * 
     * @type {Array<InvoiceEventResponseDtoOutput>}
     * @memberof ListInvoiceEvents200Response
     */
    data: Array<InvoiceEventResponseDtoOutput>;
    /**
     * 
     * @type {ListEvents200ResponseMeta}
     * @memberof ListInvoiceEvents200Response
     */
    meta: ListEvents200ResponseMeta;
}

/**
 * Check if a given object implements the ListInvoiceEvents200Response interface.
 */
export function instanceOfListInvoiceEvents200Response(value: object): value is ListInvoiceEvents200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ListInvoiceEvents200ResponseFromJSON(json: any): ListInvoiceEvents200Response {
    return ListInvoiceEvents200ResponseFromJSONTyped(json, false);
}

export function ListInvoiceEvents200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListInvoiceEvents200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': ((json['data'] as Array<any>).map(InvoiceEventResponseDtoOutputFromJSON)),
        'meta': ListEvents200ResponseMetaFromJSON(json['meta']),
    };
}

export function ListInvoiceEvents200ResponseToJSON(json: any): ListInvoiceEvents200Response {
    return ListInvoiceEvents200ResponseToJSONTyped(json, false);
}

export function ListInvoiceEvents200ResponseToJSONTyped(value?: ListInvoiceEvents200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ((value['data'] as Array<any>).map(InvoiceEventResponseDtoOutputToJSON)),
        'meta': ListEvents200ResponseMetaToJSON(value['meta']),
    };
}

