/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebhookEndpointPageResponseOutput } from './WebhookEndpointPageResponseOutput';
import {
    WebhookEndpointPageResponseOutputFromJSON,
    WebhookEndpointPageResponseOutputFromJSONTyped,
    WebhookEndpointPageResponseOutputToJSON,
    WebhookEndpointPageResponseOutputToJSONTyped,
} from './WebhookEndpointPageResponseOutput';
import type { ListEvents200ResponseMeta } from './ListEvents200ResponseMeta';
import {
    ListEvents200ResponseMetaFromJSON,
    ListEvents200ResponseMetaFromJSONTyped,
    ListEvents200ResponseMetaToJSON,
    ListEvents200ResponseMetaToJSONTyped,
} from './ListEvents200ResponseMeta';

/**
 * 
 * @export
 * @interface ListWebhookEndpoints200Response
 */
export interface ListWebhookEndpoints200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ListWebhookEndpoints200Response
     */
    success: boolean;
    /**
     * 
     * @type {WebhookEndpointPageResponseOutput}
     * @memberof ListWebhookEndpoints200Response
     */
    data: WebhookEndpointPageResponseOutput;
    /**
     * 
     * @type {ListEvents200ResponseMeta}
     * @memberof ListWebhookEndpoints200Response
     */
    meta: ListEvents200ResponseMeta;
}

/**
 * Check if a given object implements the ListWebhookEndpoints200Response interface.
 */
export function instanceOfListWebhookEndpoints200Response(value: object): value is ListWebhookEndpoints200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ListWebhookEndpoints200ResponseFromJSON(json: any): ListWebhookEndpoints200Response {
    return ListWebhookEndpoints200ResponseFromJSONTyped(json, false);
}

export function ListWebhookEndpoints200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListWebhookEndpoints200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': WebhookEndpointPageResponseOutputFromJSON(json['data']),
        'meta': ListEvents200ResponseMetaFromJSON(json['meta']),
    };
}

export function ListWebhookEndpoints200ResponseToJSON(json: any): ListWebhookEndpoints200Response {
    return ListWebhookEndpoints200ResponseToJSONTyped(json, false);
}

export function ListWebhookEndpoints200ResponseToJSONTyped(value?: ListWebhookEndpoints200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': WebhookEndpointPageResponseOutputToJSON(value['data']),
        'meta': ListEvents200ResponseMetaToJSON(value['meta']),
    };
}

