/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListEvents200ResponseMeta } from './ListEvents200ResponseMeta';
import {
    ListEvents200ResponseMetaFromJSON,
    ListEvents200ResponseMetaFromJSONTyped,
    ListEvents200ResponseMetaToJSON,
    ListEvents200ResponseMetaToJSONTyped,
} from './ListEvents200ResponseMeta';
import type { WebhookDeliveryResponseDtoOutput } from './WebhookDeliveryResponseDtoOutput';
import {
    WebhookDeliveryResponseDtoOutputFromJSON,
    WebhookDeliveryResponseDtoOutputFromJSONTyped,
    WebhookDeliveryResponseDtoOutputToJSON,
    WebhookDeliveryResponseDtoOutputToJSONTyped,
} from './WebhookDeliveryResponseDtoOutput';

/**
 * 
 * @export
 * @interface ListWebhookDeliveries200Response
 */
export interface ListWebhookDeliveries200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ListWebhookDeliveries200Response
     */
    success: boolean;
    /**
     * 
     * @type {Array<WebhookDeliveryResponseDtoOutput>}
     * @memberof ListWebhookDeliveries200Response
     */
    data: Array<WebhookDeliveryResponseDtoOutput>;
    /**
     * 
     * @type {ListEvents200ResponseMeta}
     * @memberof ListWebhookDeliveries200Response
     */
    meta: ListEvents200ResponseMeta;
}

/**
 * Check if a given object implements the ListWebhookDeliveries200Response interface.
 */
export function instanceOfListWebhookDeliveries200Response(value: object): value is ListWebhookDeliveries200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ListWebhookDeliveries200ResponseFromJSON(json: any): ListWebhookDeliveries200Response {
    return ListWebhookDeliveries200ResponseFromJSONTyped(json, false);
}

export function ListWebhookDeliveries200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListWebhookDeliveries200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': ((json['data'] as Array<any>).map(WebhookDeliveryResponseDtoOutputFromJSON)),
        'meta': ListEvents200ResponseMetaFromJSON(json['meta']),
    };
}

export function ListWebhookDeliveries200ResponseToJSON(json: any): ListWebhookDeliveries200Response {
    return ListWebhookDeliveries200ResponseToJSONTyped(json, false);
}

export function ListWebhookDeliveries200ResponseToJSONTyped(value?: ListWebhookDeliveries200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ((value['data'] as Array<any>).map(WebhookDeliveryResponseDtoOutputToJSON)),
        'meta': ListEvents200ResponseMetaToJSON(value['meta']),
    };
}

