/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListEvents200ResponseMeta
 */
export interface ListEvents200ResponseMeta {
    /**
     * 
     * @type {string}
     * @memberof ListEvents200ResponseMeta
     */
    requestId: string;
}

/**
 * Check if a given object implements the ListEvents200ResponseMeta interface.
 */
export function instanceOfListEvents200ResponseMeta(value: object): value is ListEvents200ResponseMeta {
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    return true;
}

export function ListEvents200ResponseMetaFromJSON(json: any): ListEvents200ResponseMeta {
    return ListEvents200ResponseMetaFromJSONTyped(json, false);
}

export function ListEvents200ResponseMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListEvents200ResponseMeta {
    if (json == null) {
        return json;
    }
    return {
        
        'requestId': json['requestId'],
    };
}

export function ListEvents200ResponseMetaToJSON(json: any): ListEvents200ResponseMeta {
    return ListEvents200ResponseMetaToJSONTyped(json, false);
}

export function ListEvents200ResponseMetaToJSONTyped(value?: ListEvents200ResponseMeta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'requestId': value['requestId'],
    };
}

