/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListEvents200ResponseMeta } from './ListEvents200ResponseMeta';
import {
    ListEvents200ResponseMetaFromJSON,
    ListEvents200ResponseMetaFromJSONTyped,
    ListEvents200ResponseMetaToJSON,
    ListEvents200ResponseMetaToJSONTyped,
} from './ListEvents200ResponseMeta';
import type { InvoicePageResponseOutput } from './InvoicePageResponseOutput';
import {
    InvoicePageResponseOutputFromJSON,
    InvoicePageResponseOutputFromJSONTyped,
    InvoicePageResponseOutputToJSON,
    InvoicePageResponseOutputToJSONTyped,
} from './InvoicePageResponseOutput';

/**
 * 
 * @export
 * @interface ListInvoices200Response
 */
export interface ListInvoices200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ListInvoices200Response
     */
    success: boolean;
    /**
     * 
     * @type {InvoicePageResponseOutput}
     * @memberof ListInvoices200Response
     */
    data: InvoicePageResponseOutput;
    /**
     * 
     * @type {ListEvents200ResponseMeta}
     * @memberof ListInvoices200Response
     */
    meta: ListEvents200ResponseMeta;
}

/**
 * Check if a given object implements the ListInvoices200Response interface.
 */
export function instanceOfListInvoices200Response(value: object): value is ListInvoices200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ListInvoices200ResponseFromJSON(json: any): ListInvoices200Response {
    return ListInvoices200ResponseFromJSONTyped(json, false);
}

export function ListInvoices200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListInvoices200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': InvoicePageResponseOutputFromJSON(json['data']),
        'meta': ListEvents200ResponseMetaFromJSON(json['meta']),
    };
}

export function ListInvoices200ResponseToJSON(json: any): ListInvoices200Response {
    return ListInvoices200ResponseToJSONTyped(json, false);
}

export function ListInvoices200ResponseToJSONTyped(value?: ListInvoices200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': InvoicePageResponseOutputToJSON(value['data']),
        'meta': ListEvents200ResponseMetaToJSON(value['meta']),
    };
}

