/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EventPageResponseOutput } from './EventPageResponseOutput';
import {
    EventPageResponseOutputFromJSON,
    EventPageResponseOutputFromJSONTyped,
    EventPageResponseOutputToJSON,
    EventPageResponseOutputToJSONTyped,
} from './EventPageResponseOutput';
import type { ListEvents200ResponseMeta } from './ListEvents200ResponseMeta';
import {
    ListEvents200ResponseMetaFromJSON,
    ListEvents200ResponseMetaFromJSONTyped,
    ListEvents200ResponseMetaToJSON,
    ListEvents200ResponseMetaToJSONTyped,
} from './ListEvents200ResponseMeta';

/**
 * 
 * @export
 * @interface ListEvents200Response
 */
export interface ListEvents200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ListEvents200Response
     */
    success: boolean;
    /**
     * 
     * @type {EventPageResponseOutput}
     * @memberof ListEvents200Response
     */
    data: EventPageResponseOutput;
    /**
     * 
     * @type {ListEvents200ResponseMeta}
     * @memberof ListEvents200Response
     */
    meta: ListEvents200ResponseMeta;
}

/**
 * Check if a given object implements the ListEvents200Response interface.
 */
export function instanceOfListEvents200Response(value: object): value is ListEvents200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ListEvents200ResponseFromJSON(json: any): ListEvents200Response {
    return ListEvents200ResponseFromJSONTyped(json, false);
}

export function ListEvents200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListEvents200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': EventPageResponseOutputFromJSON(json['data']),
        'meta': ListEvents200ResponseMetaFromJSON(json['meta']),
    };
}

export function ListEvents200ResponseToJSON(json: any): ListEvents200Response {
    return ListEvents200ResponseToJSONTyped(json, false);
}

export function ListEvents200ResponseToJSONTyped(value?: ListEvents200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': EventPageResponseOutputToJSON(value['data']),
        'meta': ListEvents200ResponseMetaToJSON(value['meta']),
    };
}

