/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListEvents200ResponseMeta } from './ListEvents200ResponseMeta';
import {
    ListEvents200ResponseMetaFromJSON,
    ListEvents200ResponseMetaFromJSONTyped,
    ListEvents200ResponseMetaToJSON,
    ListEvents200ResponseMetaToJSONTyped,
} from './ListEvents200ResponseMeta';
import type { SubscriptionPageResponseOutput } from './SubscriptionPageResponseOutput';
import {
    SubscriptionPageResponseOutputFromJSON,
    SubscriptionPageResponseOutputFromJSONTyped,
    SubscriptionPageResponseOutputToJSON,
    SubscriptionPageResponseOutputToJSONTyped,
} from './SubscriptionPageResponseOutput';

/**
 * 
 * @export
 * @interface ListSubscriptions200Response
 */
export interface ListSubscriptions200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ListSubscriptions200Response
     */
    success: boolean;
    /**
     * 
     * @type {SubscriptionPageResponseOutput}
     * @memberof ListSubscriptions200Response
     */
    data: SubscriptionPageResponseOutput;
    /**
     * 
     * @type {ListEvents200ResponseMeta}
     * @memberof ListSubscriptions200Response
     */
    meta: ListEvents200ResponseMeta;
}

/**
 * Check if a given object implements the ListSubscriptions200Response interface.
 */
export function instanceOfListSubscriptions200Response(value: object): value is ListSubscriptions200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ListSubscriptions200ResponseFromJSON(json: any): ListSubscriptions200Response {
    return ListSubscriptions200ResponseFromJSONTyped(json, false);
}

export function ListSubscriptions200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListSubscriptions200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': SubscriptionPageResponseOutputFromJSON(json['data']),
        'meta': ListEvents200ResponseMetaFromJSON(json['meta']),
    };
}

export function ListSubscriptions200ResponseToJSON(json: any): ListSubscriptions200Response {
    return ListSubscriptions200ResponseToJSONTyped(json, false);
}

export function ListSubscriptions200ResponseToJSONTyped(value?: ListSubscriptions200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': SubscriptionPageResponseOutputToJSON(value['data']),
        'meta': ListEvents200ResponseMetaToJSON(value['meta']),
    };
}

