/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PriceResponseOutput
 */
export interface PriceResponseOutput {
    /**
     * 
     * @type {string}
     * @memberof PriceResponseOutput
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof PriceResponseOutput
     */
    businessId: string;
    /**
     * 
     * @type {string}
     * @memberof PriceResponseOutput
     */
    environment: PriceResponseOutputEnvironmentEnum;
    /**
     * 
     * @type {string}
     * @memberof PriceResponseOutput
     */
    productId: string;
    /**
     * 
     * @type {string}
     * @memberof PriceResponseOutput
     */
    nickname: string | null;
    /**
     * 
     * @type {string}
     * @memberof PriceResponseOutput
     */
    amountPaisa: string;
    /**
     * 
     * @type {string}
     * @memberof PriceResponseOutput
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof PriceResponseOutput
     */
    interval: PriceResponseOutputIntervalEnum;
    /**
     * 
     * @type {number}
     * @memberof PriceResponseOutput
     */
    intervalCount: number;
    /**
     * 
     * @type {number}
     * @memberof PriceResponseOutput
     */
    trialDays: number;
    /**
     * 
     * @type {boolean}
     * @memberof PriceResponseOutput
     */
    active: boolean;
    /**
     * 
     * @type {any}
     * @memberof PriceResponseOutput
     */
    metadata: any | null;
    /**
     * 
     * @type {Date}
     * @memberof PriceResponseOutput
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof PriceResponseOutput
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const PriceResponseOutputEnvironmentEnum = {
    sandbox: 'sandbox',
    live: 'live'
} as const;
export type PriceResponseOutputEnvironmentEnum = typeof PriceResponseOutputEnvironmentEnum[keyof typeof PriceResponseOutputEnvironmentEnum];

/**
 * @export
 */
export const PriceResponseOutputIntervalEnum = {
    day: 'day',
    week: 'week',
    month: 'month',
    year: 'year'
} as const;
export type PriceResponseOutputIntervalEnum = typeof PriceResponseOutputIntervalEnum[keyof typeof PriceResponseOutputIntervalEnum];


/**
 * Check if a given object implements the PriceResponseOutput interface.
 */
export function instanceOfPriceResponseOutput(value: object): value is PriceResponseOutput {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('businessId' in value) || value['businessId'] === undefined) return false;
    if (!('environment' in value) || value['environment'] === undefined) return false;
    if (!('productId' in value) || value['productId'] === undefined) return false;
    if (!('nickname' in value) || value['nickname'] === undefined) return false;
    if (!('amountPaisa' in value) || value['amountPaisa'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('interval' in value) || value['interval'] === undefined) return false;
    if (!('intervalCount' in value) || value['intervalCount'] === undefined) return false;
    if (!('trialDays' in value) || value['trialDays'] === undefined) return false;
    if (!('active' in value) || value['active'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function PriceResponseOutputFromJSON(json: any): PriceResponseOutput {
    return PriceResponseOutputFromJSONTyped(json, false);
}

export function PriceResponseOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceResponseOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'businessId': json['businessId'],
        'environment': json['environment'],
        'productId': json['productId'],
        'nickname': json['nickname'],
        'amountPaisa': json['amountPaisa'],
        'currency': json['currency'],
        'interval': json['interval'],
        'intervalCount': json['intervalCount'],
        'trialDays': json['trialDays'],
        'active': json['active'],
        'metadata': json['metadata'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function PriceResponseOutputToJSON(json: any): PriceResponseOutput {
    return PriceResponseOutputToJSONTyped(json, false);
}

export function PriceResponseOutputToJSONTyped(value?: PriceResponseOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'businessId': value['businessId'],
        'environment': value['environment'],
        'productId': value['productId'],
        'nickname': value['nickname'],
        'amountPaisa': value['amountPaisa'],
        'currency': value['currency'],
        'interval': value['interval'],
        'intervalCount': value['intervalCount'],
        'trialDays': value['trialDays'],
        'active': value['active'],
        'metadata': value['metadata'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

