/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PriceArchiveResponseOutput
 */
export interface PriceArchiveResponseOutput {
    /**
     * 
     * @type {boolean}
     * @memberof PriceArchiveResponseOutput
     */
    archived: boolean;
    /**
     * 
     * @type {string}
     * @memberof PriceArchiveResponseOutput
     */
    priceId: string;
}

/**
 * Check if a given object implements the PriceArchiveResponseOutput interface.
 */
export function instanceOfPriceArchiveResponseOutput(value: object): value is PriceArchiveResponseOutput {
    if (!('archived' in value) || value['archived'] === undefined) return false;
    if (!('priceId' in value) || value['priceId'] === undefined) return false;
    return true;
}

export function PriceArchiveResponseOutputFromJSON(json: any): PriceArchiveResponseOutput {
    return PriceArchiveResponseOutputFromJSONTyped(json, false);
}

export function PriceArchiveResponseOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): PriceArchiveResponseOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'archived': json['archived'],
        'priceId': json['priceId'],
    };
}

export function PriceArchiveResponseOutputToJSON(json: any): PriceArchiveResponseOutput {
    return PriceArchiveResponseOutputToJSONTyped(json, false);
}

export function PriceArchiveResponseOutputToJSONTyped(value?: PriceArchiveResponseOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'archived': value['archived'],
        'priceId': value['priceId'],
    };
}

