/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PriceResponseOutput } from './PriceResponseOutput';
import {
    PriceResponseOutputFromJSON,
    PriceResponseOutputFromJSONTyped,
    PriceResponseOutputToJSON,
    PriceResponseOutputToJSONTyped,
} from './PriceResponseOutput';

/**
 * 
 * @export
 * @interface PricePageResponseOutput
 */
export interface PricePageResponseOutput {
    /**
     * 
     * @type {Array<PriceResponseOutput>}
     * @memberof PricePageResponseOutput
     */
    items: Array<PriceResponseOutput>;
    /**
     * 
     * @type {string}
     * @memberof PricePageResponseOutput
     */
    nextCursor: string | null;
}

/**
 * Check if a given object implements the PricePageResponseOutput interface.
 */
export function instanceOfPricePageResponseOutput(value: object): value is PricePageResponseOutput {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
    return true;
}

export function PricePageResponseOutputFromJSON(json: any): PricePageResponseOutput {
    return PricePageResponseOutputFromJSONTyped(json, false);
}

export function PricePageResponseOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): PricePageResponseOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(PriceResponseOutputFromJSON)),
        'nextCursor': json['nextCursor'],
    };
}

export function PricePageResponseOutputToJSON(json: any): PricePageResponseOutput {
    return PricePageResponseOutputToJSONTyped(json, false);
}

export function PricePageResponseOutputToJSONTyped(value?: PricePageResponseOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(PriceResponseOutputToJSON)),
        'nextCursor': value['nextCursor'],
    };
}

