/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductResponseOutput
 */
export interface ProductResponseOutput {
    /**
     * 
     * @type {string}
     * @memberof ProductResponseOutput
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ProductResponseOutput
     */
    businessId: string;
    /**
     * 
     * @type {string}
     * @memberof ProductResponseOutput
     */
    environment: ProductResponseOutputEnvironmentEnum;
    /**
     * 
     * @type {string}
     * @memberof ProductResponseOutput
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ProductResponseOutput
     */
    description: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ProductResponseOutput
     */
    active: boolean;
    /**
     * 
     * @type {string}
     * @memberof ProductResponseOutput
     */
    imageUrl: string | null;
    /**
     * 
     * @type {any}
     * @memberof ProductResponseOutput
     */
    metadata: any | null;
    /**
     * 
     * @type {Date}
     * @memberof ProductResponseOutput
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProductResponseOutput
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const ProductResponseOutputEnvironmentEnum = {
    sandbox: 'sandbox',
    live: 'live'
} as const;
export type ProductResponseOutputEnvironmentEnum = typeof ProductResponseOutputEnvironmentEnum[keyof typeof ProductResponseOutputEnvironmentEnum];


/**
 * Check if a given object implements the ProductResponseOutput interface.
 */
export function instanceOfProductResponseOutput(value: object): value is ProductResponseOutput {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('businessId' in value) || value['businessId'] === undefined) return false;
    if (!('environment' in value) || value['environment'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('active' in value) || value['active'] === undefined) return false;
    if (!('imageUrl' in value) || value['imageUrl'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ProductResponseOutputFromJSON(json: any): ProductResponseOutput {
    return ProductResponseOutputFromJSONTyped(json, false);
}

export function ProductResponseOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductResponseOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'businessId': json['businessId'],
        'environment': json['environment'],
        'name': json['name'],
        'description': json['description'],
        'active': json['active'],
        'imageUrl': json['imageUrl'],
        'metadata': json['metadata'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function ProductResponseOutputToJSON(json: any): ProductResponseOutput {
    return ProductResponseOutputToJSONTyped(json, false);
}

export function ProductResponseOutputToJSONTyped(value?: ProductResponseOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'businessId': value['businessId'],
        'environment': value['environment'],
        'name': value['name'],
        'description': value['description'],
        'active': value['active'],
        'imageUrl': value['imageUrl'],
        'metadata': value['metadata'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

