/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductArchiveResponseOutput
 */
export interface ProductArchiveResponseOutput {
    /**
     * 
     * @type {boolean}
     * @memberof ProductArchiveResponseOutput
     */
    archived: boolean;
    /**
     * 
     * @type {string}
     * @memberof ProductArchiveResponseOutput
     */
    productId: string;
}

/**
 * Check if a given object implements the ProductArchiveResponseOutput interface.
 */
export function instanceOfProductArchiveResponseOutput(value: object): value is ProductArchiveResponseOutput {
    if (!('archived' in value) || value['archived'] === undefined) return false;
    if (!('productId' in value) || value['productId'] === undefined) return false;
    return true;
}

export function ProductArchiveResponseOutputFromJSON(json: any): ProductArchiveResponseOutput {
    return ProductArchiveResponseOutputFromJSONTyped(json, false);
}

export function ProductArchiveResponseOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductArchiveResponseOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'archived': json['archived'],
        'productId': json['productId'],
    };
}

export function ProductArchiveResponseOutputToJSON(json: any): ProductArchiveResponseOutput {
    return ProductArchiveResponseOutputToJSONTyped(json, false);
}

export function ProductArchiveResponseOutputToJSONTyped(value?: ProductArchiveResponseOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'archived': value['archived'],
        'productId': value['productId'],
    };
}

