/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductResponseOutput } from './ProductResponseOutput';
import {
    ProductResponseOutputFromJSON,
    ProductResponseOutputFromJSONTyped,
    ProductResponseOutputToJSON,
    ProductResponseOutputToJSONTyped,
} from './ProductResponseOutput';

/**
 * 
 * @export
 * @interface ProductPageResponseOutput
 */
export interface ProductPageResponseOutput {
    /**
     * 
     * @type {Array<ProductResponseOutput>}
     * @memberof ProductPageResponseOutput
     */
    items: Array<ProductResponseOutput>;
    /**
     * 
     * @type {string}
     * @memberof ProductPageResponseOutput
     */
    nextCursor: string | null;
}

/**
 * Check if a given object implements the ProductPageResponseOutput interface.
 */
export function instanceOfProductPageResponseOutput(value: object): value is ProductPageResponseOutput {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
    return true;
}

export function ProductPageResponseOutputFromJSON(json: any): ProductPageResponseOutput {
    return ProductPageResponseOutputFromJSONTyped(json, false);
}

export function ProductPageResponseOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductPageResponseOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(ProductResponseOutputFromJSON)),
        'nextCursor': json['nextCursor'],
    };
}

export function ProductPageResponseOutputToJSON(json: any): ProductPageResponseOutput {
    return ProductPageResponseOutputToJSONTyped(json, false);
}

export function ProductPageResponseOutputToJSONTyped(value?: ProductPageResponseOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(ProductResponseOutputToJSON)),
        'nextCursor': value['nextCursor'],
    };
}

