/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReplayWebhookResponseOutput
 */
export interface ReplayWebhookResponseOutput {
    /**
     * 
     * @type {string}
     * @memberof ReplayWebhookResponseOutput
     */
    message: string;
    /**
     * 
     * @type {number}
     * @memberof ReplayWebhookResponseOutput
     */
    replayed_count: number;
}

/**
 * Check if a given object implements the ReplayWebhookResponseOutput interface.
 */
export function instanceOfReplayWebhookResponseOutput(value: object): value is ReplayWebhookResponseOutput {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('replayed_count' in value) || value['replayed_count'] === undefined) return false;
    return true;
}

export function ReplayWebhookResponseOutputFromJSON(json: any): ReplayWebhookResponseOutput {
    return ReplayWebhookResponseOutputFromJSONTyped(json, false);
}

export function ReplayWebhookResponseOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReplayWebhookResponseOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'replayed_count': json['replayed_count'],
    };
}

export function ReplayWebhookResponseOutputToJSON(json: any): ReplayWebhookResponseOutput {
    return ReplayWebhookResponseOutputToJSONTyped(json, false);
}

export function ReplayWebhookResponseOutputToJSONTyped(value?: ReplayWebhookResponseOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'replayed_count': value['replayed_count'],
    };
}

