/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReplayWebhookResponseOutput } from './ReplayWebhookResponseOutput';
import {
    ReplayWebhookResponseOutputFromJSON,
    ReplayWebhookResponseOutputFromJSONTyped,
    ReplayWebhookResponseOutputToJSON,
    ReplayWebhookResponseOutputToJSONTyped,
} from './ReplayWebhookResponseOutput';
import type { ListEvents200ResponseMeta } from './ListEvents200ResponseMeta';
import {
    ListEvents200ResponseMetaFromJSON,
    ListEvents200ResponseMetaFromJSONTyped,
    ListEvents200ResponseMetaToJSON,
    ListEvents200ResponseMetaToJSONTyped,
} from './ListEvents200ResponseMeta';

/**
 * 
 * @export
 * @interface ReplayWebhookDeliveries200Response
 */
export interface ReplayWebhookDeliveries200Response {
    /**
     * 
     * @type {boolean}
     * @memberof ReplayWebhookDeliveries200Response
     */
    success: boolean;
    /**
     * 
     * @type {ReplayWebhookResponseOutput}
     * @memberof ReplayWebhookDeliveries200Response
     */
    data: ReplayWebhookResponseOutput;
    /**
     * 
     * @type {ListEvents200ResponseMeta}
     * @memberof ReplayWebhookDeliveries200Response
     */
    meta: ListEvents200ResponseMeta;
}

/**
 * Check if a given object implements the ReplayWebhookDeliveries200Response interface.
 */
export function instanceOfReplayWebhookDeliveries200Response(value: object): value is ReplayWebhookDeliveries200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function ReplayWebhookDeliveries200ResponseFromJSON(json: any): ReplayWebhookDeliveries200Response {
    return ReplayWebhookDeliveries200ResponseFromJSONTyped(json, false);
}

export function ReplayWebhookDeliveries200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReplayWebhookDeliveries200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': ReplayWebhookResponseOutputFromJSON(json['data']),
        'meta': ListEvents200ResponseMetaFromJSON(json['meta']),
    };
}

export function ReplayWebhookDeliveries200ResponseToJSON(json: any): ReplayWebhookDeliveries200Response {
    return ReplayWebhookDeliveries200ResponseToJSONTyped(json, false);
}

export function ReplayWebhookDeliveries200ResponseToJSONTyped(value?: ReplayWebhookDeliveries200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': ReplayWebhookResponseOutputToJSON(value['data']),
        'meta': ListEvents200ResponseMetaToJSON(value['meta']),
    };
}

