/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RotateWebhookSecretResponseOutput
 */
export interface RotateWebhookSecretResponseOutput {
    /**
     * 
     * @type {string}
     * @memberof RotateWebhookSecretResponseOutput
     */
    secret: string;
}

/**
 * Check if a given object implements the RotateWebhookSecretResponseOutput interface.
 */
export function instanceOfRotateWebhookSecretResponseOutput(value: object): value is RotateWebhookSecretResponseOutput {
    if (!('secret' in value) || value['secret'] === undefined) return false;
    return true;
}

export function RotateWebhookSecretResponseOutputFromJSON(json: any): RotateWebhookSecretResponseOutput {
    return RotateWebhookSecretResponseOutputFromJSONTyped(json, false);
}

export function RotateWebhookSecretResponseOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): RotateWebhookSecretResponseOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'secret': json['secret'],
    };
}

export function RotateWebhookSecretResponseOutputToJSON(json: any): RotateWebhookSecretResponseOutput {
    return RotateWebhookSecretResponseOutputToJSONTyped(json, false);
}

export function RotateWebhookSecretResponseOutputToJSONTyped(value?: RotateWebhookSecretResponseOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'secret': value['secret'],
    };
}

