/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListEvents200ResponseMeta } from './ListEvents200ResponseMeta';
import {
    ListEvents200ResponseMetaFromJSON,
    ListEvents200ResponseMetaFromJSONTyped,
    ListEvents200ResponseMetaToJSON,
    ListEvents200ResponseMetaToJSONTyped,
} from './ListEvents200ResponseMeta';
import type { RotateWebhookSecretResponseOutput } from './RotateWebhookSecretResponseOutput';
import {
    RotateWebhookSecretResponseOutputFromJSON,
    RotateWebhookSecretResponseOutputFromJSONTyped,
    RotateWebhookSecretResponseOutputToJSON,
    RotateWebhookSecretResponseOutputToJSONTyped,
} from './RotateWebhookSecretResponseOutput';

/**
 * 
 * @export
 * @interface RotateWebhookSecret200Response
 */
export interface RotateWebhookSecret200Response {
    /**
     * 
     * @type {boolean}
     * @memberof RotateWebhookSecret200Response
     */
    success: boolean;
    /**
     * 
     * @type {RotateWebhookSecretResponseOutput}
     * @memberof RotateWebhookSecret200Response
     */
    data: RotateWebhookSecretResponseOutput;
    /**
     * 
     * @type {ListEvents200ResponseMeta}
     * @memberof RotateWebhookSecret200Response
     */
    meta: ListEvents200ResponseMeta;
}

/**
 * Check if a given object implements the RotateWebhookSecret200Response interface.
 */
export function instanceOfRotateWebhookSecret200Response(value: object): value is RotateWebhookSecret200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function RotateWebhookSecret200ResponseFromJSON(json: any): RotateWebhookSecret200Response {
    return RotateWebhookSecret200ResponseFromJSONTyped(json, false);
}

export function RotateWebhookSecret200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RotateWebhookSecret200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': RotateWebhookSecretResponseOutputFromJSON(json['data']),
        'meta': ListEvents200ResponseMetaFromJSON(json['meta']),
    };
}

export function RotateWebhookSecret200ResponseToJSON(json: any): RotateWebhookSecret200Response {
    return RotateWebhookSecret200ResponseToJSONTyped(json, false);
}

export function RotateWebhookSecret200ResponseToJSONTyped(value?: RotateWebhookSecret200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': RotateWebhookSecretResponseOutputToJSON(value['data']),
        'meta': ListEvents200ResponseMetaToJSON(value['meta']),
    };
}

