/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InvoiceResponseOutput } from './InvoiceResponseOutput';
import {
    InvoiceResponseOutputFromJSON,
    InvoiceResponseOutputFromJSONTyped,
    InvoiceResponseOutputToJSON,
    InvoiceResponseOutputToJSONTyped,
} from './InvoiceResponseOutput';

/**
 * 
 * @export
 * @interface SendInvoiceResponseOutput
 */
export interface SendInvoiceResponseOutput {
    /**
     * 
     * @type {InvoiceResponseOutput}
     * @memberof SendInvoiceResponseOutput
     */
    invoice: InvoiceResponseOutput;
    /**
     * 
     * @type {string}
     * @memberof SendInvoiceResponseOutput
     */
    sent_to_email?: string | null;
}

/**
 * Check if a given object implements the SendInvoiceResponseOutput interface.
 */
export function instanceOfSendInvoiceResponseOutput(value: object): value is SendInvoiceResponseOutput {
    if (!('invoice' in value) || value['invoice'] === undefined) return false;
    return true;
}

export function SendInvoiceResponseOutputFromJSON(json: any): SendInvoiceResponseOutput {
    return SendInvoiceResponseOutputFromJSONTyped(json, false);
}

export function SendInvoiceResponseOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendInvoiceResponseOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'invoice': InvoiceResponseOutputFromJSON(json['invoice']),
        'sent_to_email': json['sent_to_email'] == null ? undefined : json['sent_to_email'],
    };
}

export function SendInvoiceResponseOutputToJSON(json: any): SendInvoiceResponseOutput {
    return SendInvoiceResponseOutputToJSONTyped(json, false);
}

export function SendInvoiceResponseOutputToJSONTyped(value?: SendInvoiceResponseOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'invoice': InvoiceResponseOutputToJSON(value['invoice']),
        'sent_to_email': value['sent_to_email'],
    };
}

