/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListEvents200ResponseMeta } from './ListEvents200ResponseMeta';
import {
    ListEvents200ResponseMetaFromJSON,
    ListEvents200ResponseMetaFromJSONTyped,
    ListEvents200ResponseMetaToJSON,
    ListEvents200ResponseMetaToJSONTyped,
} from './ListEvents200ResponseMeta';
import type { TestWebhookResponseOutput } from './TestWebhookResponseOutput';
import {
    TestWebhookResponseOutputFromJSON,
    TestWebhookResponseOutputFromJSONTyped,
    TestWebhookResponseOutputToJSON,
    TestWebhookResponseOutputToJSONTyped,
} from './TestWebhookResponseOutput';

/**
 * 
 * @export
 * @interface SendTestWebhook200Response
 */
export interface SendTestWebhook200Response {
    /**
     * 
     * @type {boolean}
     * @memberof SendTestWebhook200Response
     */
    success: boolean;
    /**
     * 
     * @type {TestWebhookResponseOutput}
     * @memberof SendTestWebhook200Response
     */
    data: TestWebhookResponseOutput;
    /**
     * 
     * @type {ListEvents200ResponseMeta}
     * @memberof SendTestWebhook200Response
     */
    meta: ListEvents200ResponseMeta;
}

/**
 * Check if a given object implements the SendTestWebhook200Response interface.
 */
export function instanceOfSendTestWebhook200Response(value: object): value is SendTestWebhook200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function SendTestWebhook200ResponseFromJSON(json: any): SendTestWebhook200Response {
    return SendTestWebhook200ResponseFromJSONTyped(json, false);
}

export function SendTestWebhook200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendTestWebhook200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': TestWebhookResponseOutputFromJSON(json['data']),
        'meta': ListEvents200ResponseMetaFromJSON(json['meta']),
    };
}

export function SendTestWebhook200ResponseToJSON(json: any): SendTestWebhook200Response {
    return SendTestWebhook200ResponseToJSONTyped(json, false);
}

export function SendTestWebhook200ResponseToJSONTyped(value?: SendTestWebhook200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': TestWebhookResponseOutputToJSON(value['data']),
        'meta': ListEvents200ResponseMetaToJSON(value['meta']),
    };
}

