/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SendInvoiceResponseOutput } from './SendInvoiceResponseOutput';
import {
    SendInvoiceResponseOutputFromJSON,
    SendInvoiceResponseOutputFromJSONTyped,
    SendInvoiceResponseOutputToJSON,
    SendInvoiceResponseOutputToJSONTyped,
} from './SendInvoiceResponseOutput';
import type { ListEvents200ResponseMeta } from './ListEvents200ResponseMeta';
import {
    ListEvents200ResponseMetaFromJSON,
    ListEvents200ResponseMetaFromJSONTyped,
    ListEvents200ResponseMetaToJSON,
    ListEvents200ResponseMetaToJSONTyped,
} from './ListEvents200ResponseMeta';

/**
 * 
 * @export
 * @interface SendInvoice200Response
 */
export interface SendInvoice200Response {
    /**
     * 
     * @type {boolean}
     * @memberof SendInvoice200Response
     */
    success: boolean;
    /**
     * 
     * @type {SendInvoiceResponseOutput}
     * @memberof SendInvoice200Response
     */
    data: SendInvoiceResponseOutput;
    /**
     * 
     * @type {ListEvents200ResponseMeta}
     * @memberof SendInvoice200Response
     */
    meta: ListEvents200ResponseMeta;
}

/**
 * Check if a given object implements the SendInvoice200Response interface.
 */
export function instanceOfSendInvoice200Response(value: object): value is SendInvoice200Response {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function SendInvoice200ResponseFromJSON(json: any): SendInvoice200Response {
    return SendInvoice200ResponseFromJSONTyped(json, false);
}

export function SendInvoice200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendInvoice200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': SendInvoiceResponseOutputFromJSON(json['data']),
        'meta': ListEvents200ResponseMetaFromJSON(json['meta']),
    };
}

export function SendInvoice200ResponseToJSON(json: any): SendInvoice200Response {
    return SendInvoice200ResponseToJSONTyped(json, false);
}

export function SendInvoice200ResponseToJSONTyped(value?: SendInvoice200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': SendInvoiceResponseOutputToJSON(value['data']),
        'meta': ListEvents200ResponseMetaToJSON(value['meta']),
    };
}

