/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SubscriptionResponseOutput } from './SubscriptionResponseOutput';
import {
    SubscriptionResponseOutputFromJSON,
    SubscriptionResponseOutputFromJSONTyped,
    SubscriptionResponseOutputToJSON,
    SubscriptionResponseOutputToJSONTyped,
} from './SubscriptionResponseOutput';

/**
 * 
 * @export
 * @interface SubscriptionPageResponseOutput
 */
export interface SubscriptionPageResponseOutput {
    /**
     * 
     * @type {Array<SubscriptionResponseOutput>}
     * @memberof SubscriptionPageResponseOutput
     */
    items: Array<SubscriptionResponseOutput>;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionPageResponseOutput
     */
    nextCursor: string | null;
}

/**
 * Check if a given object implements the SubscriptionPageResponseOutput interface.
 */
export function instanceOfSubscriptionPageResponseOutput(value: object): value is SubscriptionPageResponseOutput {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
    return true;
}

export function SubscriptionPageResponseOutputFromJSON(json: any): SubscriptionPageResponseOutput {
    return SubscriptionPageResponseOutputFromJSONTyped(json, false);
}

export function SubscriptionPageResponseOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionPageResponseOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(SubscriptionResponseOutputFromJSON)),
        'nextCursor': json['nextCursor'],
    };
}

export function SubscriptionPageResponseOutputToJSON(json: any): SubscriptionPageResponseOutput {
    return SubscriptionPageResponseOutputToJSONTyped(json, false);
}

export function SubscriptionPageResponseOutputToJSONTyped(value?: SubscriptionPageResponseOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(SubscriptionResponseOutputToJSON)),
        'nextCursor': value['nextCursor'],
    };
}

