/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubscriptionResponseOutput
 */
export interface SubscriptionResponseOutput {
    /**
     * 
     * @type {string}
     * @memberof SubscriptionResponseOutput
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionResponseOutput
     */
    businessId: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionResponseOutput
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionResponseOutput
     */
    priceId: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionResponseOutput
     */
    customerId: string;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionResponseOutput
     */
    status: SubscriptionResponseOutputStatusEnum;
    /**
     * 
     * @type {boolean}
     * @memberof SubscriptionResponseOutput
     */
    cancelAtPeriodEnd: boolean;
    /**
     * 
     * @type {Date}
     * @memberof SubscriptionResponseOutput
     */
    trialEndAt: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof SubscriptionResponseOutput
     */
    currentPeriodStart: Date;
    /**
     * 
     * @type {Date}
     * @memberof SubscriptionResponseOutput
     */
    currentPeriodEnd: Date;
    /**
     * 
     * @type {number}
     * @memberof SubscriptionResponseOutput
     */
    retryCount: number;
    /**
     * 
     * @type {Date}
     * @memberof SubscriptionResponseOutput
     */
    nextRetryAt: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof SubscriptionResponseOutput
     */
    lastBilledAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof SubscriptionResponseOutput
     */
    billingRunId: string | null;
    /**
     * 
     * @type {any}
     * @memberof SubscriptionResponseOutput
     */
    metadata: any | null;
    /**
     * 
     * @type {Date}
     * @memberof SubscriptionResponseOutput
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof SubscriptionResponseOutput
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const SubscriptionResponseOutputStatusEnum = {
    trialing: 'trialing',
    active: 'active',
    past_due: 'past_due',
    unpaid: 'unpaid',
    cancelled: 'cancelled'
} as const;
export type SubscriptionResponseOutputStatusEnum = typeof SubscriptionResponseOutputStatusEnum[keyof typeof SubscriptionResponseOutputStatusEnum];


/**
 * Check if a given object implements the SubscriptionResponseOutput interface.
 */
export function instanceOfSubscriptionResponseOutput(value: object): value is SubscriptionResponseOutput {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('businessId' in value) || value['businessId'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('priceId' in value) || value['priceId'] === undefined) return false;
    if (!('customerId' in value) || value['customerId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('cancelAtPeriodEnd' in value) || value['cancelAtPeriodEnd'] === undefined) return false;
    if (!('trialEndAt' in value) || value['trialEndAt'] === undefined) return false;
    if (!('currentPeriodStart' in value) || value['currentPeriodStart'] === undefined) return false;
    if (!('currentPeriodEnd' in value) || value['currentPeriodEnd'] === undefined) return false;
    if (!('retryCount' in value) || value['retryCount'] === undefined) return false;
    if (!('nextRetryAt' in value) || value['nextRetryAt'] === undefined) return false;
    if (!('lastBilledAt' in value) || value['lastBilledAt'] === undefined) return false;
    if (!('billingRunId' in value) || value['billingRunId'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function SubscriptionResponseOutputFromJSON(json: any): SubscriptionResponseOutput {
    return SubscriptionResponseOutputFromJSONTyped(json, false);
}

export function SubscriptionResponseOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionResponseOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'businessId': json['businessId'],
        'userId': json['userId'],
        'priceId': json['priceId'],
        'customerId': json['customerId'],
        'status': json['status'],
        'cancelAtPeriodEnd': json['cancelAtPeriodEnd'],
        'trialEndAt': (json['trialEndAt'] == null ? null : new Date(json['trialEndAt'])),
        'currentPeriodStart': (new Date(json['currentPeriodStart'])),
        'currentPeriodEnd': (new Date(json['currentPeriodEnd'])),
        'retryCount': json['retryCount'],
        'nextRetryAt': (json['nextRetryAt'] == null ? null : new Date(json['nextRetryAt'])),
        'lastBilledAt': (json['lastBilledAt'] == null ? null : new Date(json['lastBilledAt'])),
        'billingRunId': json['billingRunId'],
        'metadata': json['metadata'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function SubscriptionResponseOutputToJSON(json: any): SubscriptionResponseOutput {
    return SubscriptionResponseOutputToJSONTyped(json, false);
}

export function SubscriptionResponseOutputToJSONTyped(value?: SubscriptionResponseOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'businessId': value['businessId'],
        'userId': value['userId'],
        'priceId': value['priceId'],
        'customerId': value['customerId'],
        'status': value['status'],
        'cancelAtPeriodEnd': value['cancelAtPeriodEnd'],
        'trialEndAt': value['trialEndAt'] == null ? value['trialEndAt'] : value['trialEndAt'].toISOString(),
        'currentPeriodStart': value['currentPeriodStart'].toISOString(),
        'currentPeriodEnd': value['currentPeriodEnd'].toISOString(),
        'retryCount': value['retryCount'],
        'nextRetryAt': value['nextRetryAt'] == null ? value['nextRetryAt'] : value['nextRetryAt'].toISOString(),
        'lastBilledAt': value['lastBilledAt'] == null ? value['lastBilledAt'] : value['lastBilledAt'].toISOString(),
        'billingRunId': value['billingRunId'],
        'metadata': value['metadata'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

