/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TestWebhookResponseOutput
 */
export interface TestWebhookResponseOutput {
    /**
     * 
     * @type {string}
     * @memberof TestWebhookResponseOutput
     */
    message: string;
    /**
     * 
     * @type {string}
     * @memberof TestWebhookResponseOutput
     */
    outbox_id: string;
}

/**
 * Check if a given object implements the TestWebhookResponseOutput interface.
 */
export function instanceOfTestWebhookResponseOutput(value: object): value is TestWebhookResponseOutput {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('outbox_id' in value) || value['outbox_id'] === undefined) return false;
    return true;
}

export function TestWebhookResponseOutputFromJSON(json: any): TestWebhookResponseOutput {
    return TestWebhookResponseOutputFromJSONTyped(json, false);
}

export function TestWebhookResponseOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): TestWebhookResponseOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'outbox_id': json['outbox_id'],
    };
}

export function TestWebhookResponseOutputToJSON(json: any): TestWebhookResponseOutput {
    return TestWebhookResponseOutputToJSONTyped(json, false);
}

export function TestWebhookResponseOutputToJSONTyped(value?: TestWebhookResponseOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'outbox_id': value['outbox_id'],
    };
}

