/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateSubscription
 */
export interface UpdateSubscription {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof UpdateSubscription
     */
    metadata?: { [key: string]: any; };
    /**
     * 
     * @type {boolean}
     * @memberof UpdateSubscription
     */
    cancelAtPeriodEnd?: boolean;
}

/**
 * Check if a given object implements the UpdateSubscription interface.
 */
export function instanceOfUpdateSubscription(value: object): value is UpdateSubscription {
    return true;
}

export function UpdateSubscriptionFromJSON(json: any): UpdateSubscription {
    return UpdateSubscriptionFromJSONTyped(json, false);
}

export function UpdateSubscriptionFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSubscription {
    if (json == null) {
        return json;
    }
    return {
        
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'cancelAtPeriodEnd': json['cancelAtPeriodEnd'] == null ? undefined : json['cancelAtPeriodEnd'],
    };
}

export function UpdateSubscriptionToJSON(json: any): UpdateSubscription {
    return UpdateSubscriptionToJSONTyped(json, false);
}

export function UpdateSubscriptionToJSONTyped(value?: UpdateSubscription | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'metadata': value['metadata'],
        'cancelAtPeriodEnd': value['cancelAtPeriodEnd'],
    };
}

