/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateWebhookEndpoint
 */
export interface UpdateWebhookEndpoint {
    /**
     * 
     * @type {string}
     * @memberof UpdateWebhookEndpoint
     */
    url?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateWebhookEndpoint
     */
    enabled_events?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateWebhookEndpoint
     */
    active?: boolean;
    /**
     * 
     * @type {{ [key: string]: string | null; }}
     * @memberof UpdateWebhookEndpoint
     */
    metadata?: { [key: string]: string | null; };
}

/**
 * Check if a given object implements the UpdateWebhookEndpoint interface.
 */
export function instanceOfUpdateWebhookEndpoint(value: object): value is UpdateWebhookEndpoint {
    return true;
}

export function UpdateWebhookEndpointFromJSON(json: any): UpdateWebhookEndpoint {
    return UpdateWebhookEndpointFromJSONTyped(json, false);
}

export function UpdateWebhookEndpointFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateWebhookEndpoint {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
        'enabled_events': json['enabled_events'] == null ? undefined : json['enabled_events'],
        'active': json['active'] == null ? undefined : json['active'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function UpdateWebhookEndpointToJSON(json: any): UpdateWebhookEndpoint {
    return UpdateWebhookEndpointToJSONTyped(json, false);
}

export function UpdateWebhookEndpointToJSONTyped(value?: UpdateWebhookEndpoint | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'enabled_events': value['enabled_events'],
        'active': value['active'],
        'metadata': value['metadata'],
    };
}

