/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateProduct
 */
export interface UpdateProduct {
    /**
     * 
     * @type {string}
     * @memberof UpdateProduct
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateProduct
     */
    description?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateProduct
     */
    active?: boolean;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof UpdateProduct
     */
    metadata?: { [key: string]: any; };
}

/**
 * Check if a given object implements the UpdateProduct interface.
 */
export function instanceOfUpdateProduct(value: object): value is UpdateProduct {
    return true;
}

export function UpdateProductFromJSON(json: any): UpdateProduct {
    return UpdateProductFromJSONTyped(json, false);
}

export function UpdateProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProduct {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'active': json['active'] == null ? undefined : json['active'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function UpdateProductToJSON(json: any): UpdateProduct {
    return UpdateProductToJSONTyped(json, false);
}

export function UpdateProductToJSONTyped(value?: UpdateProduct | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'active': value['active'],
        'metadata': value['metadata'],
    };
}

