/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdatePrice
 */
export interface UpdatePrice {
    /**
     * 
     * @type {string}
     * @memberof UpdatePrice
     */
    nickname?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePrice
     */
    amountPaisa?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePrice
     */
    currency?: UpdatePriceCurrencyEnum;
    /**
     * 
     * @type {string}
     * @memberof UpdatePrice
     */
    interval?: UpdatePriceIntervalEnum;
    /**
     * 
     * @type {number}
     * @memberof UpdatePrice
     */
    intervalCount?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdatePrice
     */
    trialDays?: number;
    /**
     * 
     * @type {boolean}
     * @memberof UpdatePrice
     */
    active?: boolean;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof UpdatePrice
     */
    metadata?: { [key: string]: any; };
}


/**
 * @export
 */
export const UpdatePriceCurrencyEnum = {
    npr: 'npr'
} as const;
export type UpdatePriceCurrencyEnum = typeof UpdatePriceCurrencyEnum[keyof typeof UpdatePriceCurrencyEnum];

/**
 * @export
 */
export const UpdatePriceIntervalEnum = {
    day: 'day',
    week: 'week',
    month: 'month',
    year: 'year'
} as const;
export type UpdatePriceIntervalEnum = typeof UpdatePriceIntervalEnum[keyof typeof UpdatePriceIntervalEnum];


/**
 * Check if a given object implements the UpdatePrice interface.
 */
export function instanceOfUpdatePrice(value: object): value is UpdatePrice {
    return true;
}

export function UpdatePriceFromJSON(json: any): UpdatePrice {
    return UpdatePriceFromJSONTyped(json, false);
}

export function UpdatePriceFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePrice {
    if (json == null) {
        return json;
    }
    return {
        
        'nickname': json['nickname'] == null ? undefined : json['nickname'],
        'amountPaisa': json['amountPaisa'] == null ? undefined : json['amountPaisa'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'interval': json['interval'] == null ? undefined : json['interval'],
        'intervalCount': json['intervalCount'] == null ? undefined : json['intervalCount'],
        'trialDays': json['trialDays'] == null ? undefined : json['trialDays'],
        'active': json['active'] == null ? undefined : json['active'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function UpdatePriceToJSON(json: any): UpdatePrice {
    return UpdatePriceToJSONTyped(json, false);
}

export function UpdatePriceToJSONTyped(value?: UpdatePrice | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nickname': value['nickname'],
        'amountPaisa': value['amountPaisa'],
        'currency': value['currency'],
        'interval': value['interval'],
        'intervalCount': value['intervalCount'],
        'trialDays': value['trialDays'],
        'active': value['active'],
        'metadata': value['metadata'],
    };
}

