/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateCustomer
 */
export interface UpdateCustomer {
    /**
     * 
     * @type {string}
     * @memberof UpdateCustomer
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCustomer
     */
    email?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof UpdateCustomer
     */
    metadata?: { [key: string]: any; };
}

/**
 * Check if a given object implements the UpdateCustomer interface.
 */
export function instanceOfUpdateCustomer(value: object): value is UpdateCustomer {
    return true;
}

export function UpdateCustomerFromJSON(json: any): UpdateCustomer {
    return UpdateCustomerFromJSONTyped(json, false);
}

export function UpdateCustomerFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCustomer {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function UpdateCustomerToJSON(json: any): UpdateCustomer {
    return UpdateCustomerToJSONTyped(json, false);
}

export function UpdateCustomerToJSONTyped(value?: UpdateCustomer | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'email': value['email'],
        'metadata': value['metadata'],
    };
}

