/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateSubscriptionRequest
 */
export interface UpdateSubscriptionRequest {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof UpdateSubscriptionRequest
     */
    metadata?: { [key: string]: any; };
    /**
     * 
     * @type {boolean}
     * @memberof UpdateSubscriptionRequest
     */
    cancelAtPeriodEnd?: boolean;
}

/**
 * Check if a given object implements the UpdateSubscriptionRequest interface.
 */
export function instanceOfUpdateSubscriptionRequest(value: object): value is UpdateSubscriptionRequest {
    return true;
}

export function UpdateSubscriptionRequestFromJSON(json: any): UpdateSubscriptionRequest {
    return UpdateSubscriptionRequestFromJSONTyped(json, false);
}

export function UpdateSubscriptionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSubscriptionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'cancelAtPeriodEnd': json['cancelAtPeriodEnd'] == null ? undefined : json['cancelAtPeriodEnd'],
    };
}

export function UpdateSubscriptionRequestToJSON(json: any): UpdateSubscriptionRequest {
    return UpdateSubscriptionRequestToJSONTyped(json, false);
}

export function UpdateSubscriptionRequestToJSONTyped(value?: UpdateSubscriptionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'metadata': value['metadata'],
        'cancelAtPeriodEnd': value['cancelAtPeriodEnd'],
    };
}

