/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateWebhookEndpointBodyDto
 */
export interface UpdateWebhookEndpointBodyDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateWebhookEndpointBodyDto
     */
    url?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateWebhookEndpointBodyDto
     */
    enabled_events?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateWebhookEndpointBodyDto
     */
    active?: boolean;
    /**
     * 
     * @type {{ [key: string]: string | null; }}
     * @memberof UpdateWebhookEndpointBodyDto
     */
    metadata?: { [key: string]: string | null; };
}

/**
 * Check if a given object implements the UpdateWebhookEndpointBodyDto interface.
 */
export function instanceOfUpdateWebhookEndpointBodyDto(value: object): value is UpdateWebhookEndpointBodyDto {
    return true;
}

export function UpdateWebhookEndpointBodyDtoFromJSON(json: any): UpdateWebhookEndpointBodyDto {
    return UpdateWebhookEndpointBodyDtoFromJSONTyped(json, false);
}

export function UpdateWebhookEndpointBodyDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateWebhookEndpointBodyDto {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
        'enabled_events': json['enabled_events'] == null ? undefined : json['enabled_events'],
        'active': json['active'] == null ? undefined : json['active'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function UpdateWebhookEndpointBodyDtoToJSON(json: any): UpdateWebhookEndpointBodyDto {
    return UpdateWebhookEndpointBodyDtoToJSONTyped(json, false);
}

export function UpdateWebhookEndpointBodyDtoToJSONTyped(value?: UpdateWebhookEndpointBodyDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
        'enabled_events': value['enabled_events'],
        'active': value['active'],
        'metadata': value['metadata'],
    };
}

