/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookEndpointWithSecretResponseOutput
 */
export interface WebhookEndpointWithSecretResponseOutput {
    /**
     * 
     * @type {string}
     * @memberof WebhookEndpointWithSecretResponseOutput
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookEndpointWithSecretResponseOutput
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookEndpointWithSecretResponseOutput
     */
    secret: string;
    /**
     * 
     * @type {any}
     * @memberof WebhookEndpointWithSecretResponseOutput
     */
    enabled_events: any | null;
    /**
     * 
     * @type {boolean}
     * @memberof WebhookEndpointWithSecretResponseOutput
     */
    active: boolean;
    /**
     * 
     * @type {any}
     * @memberof WebhookEndpointWithSecretResponseOutput
     */
    metadata: any | null;
}

/**
 * Check if a given object implements the WebhookEndpointWithSecretResponseOutput interface.
 */
export function instanceOfWebhookEndpointWithSecretResponseOutput(value: object): value is WebhookEndpointWithSecretResponseOutput {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('secret' in value) || value['secret'] === undefined) return false;
    if (!('enabled_events' in value) || value['enabled_events'] === undefined) return false;
    if (!('active' in value) || value['active'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    return true;
}

export function WebhookEndpointWithSecretResponseOutputFromJSON(json: any): WebhookEndpointWithSecretResponseOutput {
    return WebhookEndpointWithSecretResponseOutputFromJSONTyped(json, false);
}

export function WebhookEndpointWithSecretResponseOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookEndpointWithSecretResponseOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'url': json['url'],
        'secret': json['secret'],
        'enabled_events': json['enabled_events'],
        'active': json['active'],
        'metadata': json['metadata'],
    };
}

export function WebhookEndpointWithSecretResponseOutputToJSON(json: any): WebhookEndpointWithSecretResponseOutput {
    return WebhookEndpointWithSecretResponseOutputToJSONTyped(json, false);
}

export function WebhookEndpointWithSecretResponseOutputToJSONTyped(value?: WebhookEndpointWithSecretResponseOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'url': value['url'],
        'secret': value['secret'],
        'enabled_events': value['enabled_events'],
        'active': value['active'],
        'metadata': value['metadata'],
    };
}

