/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookDeliveryResponseDtoOutputResponse
 */
export interface WebhookDeliveryResponseDtoOutputResponse {
    /**
     * 
     * @type {number}
     * @memberof WebhookDeliveryResponseDtoOutputResponse
     */
    status: number;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof WebhookDeliveryResponseDtoOutputResponse
     */
    headers: { [key: string]: string; };
    /**
     * 
     * @type {any}
     * @memberof WebhookDeliveryResponseDtoOutputResponse
     */
    body: any | null;
}

/**
 * Check if a given object implements the WebhookDeliveryResponseDtoOutputResponse interface.
 */
export function instanceOfWebhookDeliveryResponseDtoOutputResponse(value: object): value is WebhookDeliveryResponseDtoOutputResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('headers' in value) || value['headers'] === undefined) return false;
    if (!('body' in value) || value['body'] === undefined) return false;
    return true;
}

export function WebhookDeliveryResponseDtoOutputResponseFromJSON(json: any): WebhookDeliveryResponseDtoOutputResponse {
    return WebhookDeliveryResponseDtoOutputResponseFromJSONTyped(json, false);
}

export function WebhookDeliveryResponseDtoOutputResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookDeliveryResponseDtoOutputResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'headers': json['headers'],
        'body': json['body'],
    };
}

export function WebhookDeliveryResponseDtoOutputResponseToJSON(json: any): WebhookDeliveryResponseDtoOutputResponse {
    return WebhookDeliveryResponseDtoOutputResponseToJSONTyped(json, false);
}

export function WebhookDeliveryResponseDtoOutputResponseToJSONTyped(value?: WebhookDeliveryResponseDtoOutputResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'headers': value['headers'],
        'body': value['body'],
    };
}

