/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebhookDeliveryResponseDtoOutputRequest } from './WebhookDeliveryResponseDtoOutputRequest';
import {
    WebhookDeliveryResponseDtoOutputRequestFromJSON,
    WebhookDeliveryResponseDtoOutputRequestFromJSONTyped,
    WebhookDeliveryResponseDtoOutputRequestToJSON,
    WebhookDeliveryResponseDtoOutputRequestToJSONTyped,
} from './WebhookDeliveryResponseDtoOutputRequest';
import type { WebhookDeliveryResponseDtoOutputResponse } from './WebhookDeliveryResponseDtoOutputResponse';
import {
    WebhookDeliveryResponseDtoOutputResponseFromJSON,
    WebhookDeliveryResponseDtoOutputResponseFromJSONTyped,
    WebhookDeliveryResponseDtoOutputResponseToJSON,
    WebhookDeliveryResponseDtoOutputResponseToJSONTyped,
} from './WebhookDeliveryResponseDtoOutputResponse';

/**
 * 
 * @export
 * @interface WebhookDeliveryResponseDtoOutput
 */
export interface WebhookDeliveryResponseDtoOutput {
    /**
     * 
     * @type {string}
     * @memberof WebhookDeliveryResponseDtoOutput
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof WebhookDeliveryResponseDtoOutput
     */
    attemptedAt: Date;
    /**
     * 
     * @type {string}
     * @memberof WebhookDeliveryResponseDtoOutput
     */
    eventId: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookDeliveryResponseDtoOutput
     */
    eventType: string;
    /**
     * 
     * @type {number}
     * @memberof WebhookDeliveryResponseDtoOutput
     */
    httpStatus?: number;
    /**
     * 
     * @type {number}
     * @memberof WebhookDeliveryResponseDtoOutput
     */
    latencyMs?: number;
    /**
     * 
     * @type {WebhookDeliveryResponseDtoOutputRequest}
     * @memberof WebhookDeliveryResponseDtoOutput
     */
    request: WebhookDeliveryResponseDtoOutputRequest;
    /**
     * 
     * @type {WebhookDeliveryResponseDtoOutputResponse}
     * @memberof WebhookDeliveryResponseDtoOutput
     */
    response?: WebhookDeliveryResponseDtoOutputResponse;
    /**
     * 
     * @type {string}
     * @memberof WebhookDeliveryResponseDtoOutput
     */
    status: WebhookDeliveryResponseDtoOutputStatusEnum;
}


/**
 * @export
 */
export const WebhookDeliveryResponseDtoOutputStatusEnum = {
    delivered: 'delivered',
    retrying: 'retrying',
    failed: 'failed',
    pending: 'pending'
} as const;
export type WebhookDeliveryResponseDtoOutputStatusEnum = typeof WebhookDeliveryResponseDtoOutputStatusEnum[keyof typeof WebhookDeliveryResponseDtoOutputStatusEnum];


/**
 * Check if a given object implements the WebhookDeliveryResponseDtoOutput interface.
 */
export function instanceOfWebhookDeliveryResponseDtoOutput(value: object): value is WebhookDeliveryResponseDtoOutput {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('attemptedAt' in value) || value['attemptedAt'] === undefined) return false;
    if (!('eventId' in value) || value['eventId'] === undefined) return false;
    if (!('eventType' in value) || value['eventType'] === undefined) return false;
    if (!('request' in value) || value['request'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function WebhookDeliveryResponseDtoOutputFromJSON(json: any): WebhookDeliveryResponseDtoOutput {
    return WebhookDeliveryResponseDtoOutputFromJSONTyped(json, false);
}

export function WebhookDeliveryResponseDtoOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookDeliveryResponseDtoOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'attemptedAt': (new Date(json['attemptedAt'])),
        'eventId': json['eventId'],
        'eventType': json['eventType'],
        'httpStatus': json['httpStatus'] == null ? undefined : json['httpStatus'],
        'latencyMs': json['latencyMs'] == null ? undefined : json['latencyMs'],
        'request': WebhookDeliveryResponseDtoOutputRequestFromJSON(json['request']),
        'response': json['response'] == null ? undefined : WebhookDeliveryResponseDtoOutputResponseFromJSON(json['response']),
        'status': json['status'],
    };
}

export function WebhookDeliveryResponseDtoOutputToJSON(json: any): WebhookDeliveryResponseDtoOutput {
    return WebhookDeliveryResponseDtoOutputToJSONTyped(json, false);
}

export function WebhookDeliveryResponseDtoOutputToJSONTyped(value?: WebhookDeliveryResponseDtoOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'attemptedAt': value['attemptedAt'].toISOString(),
        'eventId': value['eventId'],
        'eventType': value['eventType'],
        'httpStatus': value['httpStatus'],
        'latencyMs': value['latencyMs'],
        'request': WebhookDeliveryResponseDtoOutputRequestToJSON(value['request']),
        'response': WebhookDeliveryResponseDtoOutputResponseToJSON(value['response']),
        'status': value['status'],
    };
}

