/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookDeliveryResponseDtoOutputRequest
 */
export interface WebhookDeliveryResponseDtoOutputRequest {
    /**
     * 
     * @type {string}
     * @memberof WebhookDeliveryResponseDtoOutputRequest
     */
    method: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookDeliveryResponseDtoOutputRequest
     */
    url: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof WebhookDeliveryResponseDtoOutputRequest
     */
    headers: { [key: string]: string; };
    /**
     * 
     * @type {any}
     * @memberof WebhookDeliveryResponseDtoOutputRequest
     */
    body: any | null;
}

/**
 * Check if a given object implements the WebhookDeliveryResponseDtoOutputRequest interface.
 */
export function instanceOfWebhookDeliveryResponseDtoOutputRequest(value: object): value is WebhookDeliveryResponseDtoOutputRequest {
    if (!('method' in value) || value['method'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('headers' in value) || value['headers'] === undefined) return false;
    if (!('body' in value) || value['body'] === undefined) return false;
    return true;
}

export function WebhookDeliveryResponseDtoOutputRequestFromJSON(json: any): WebhookDeliveryResponseDtoOutputRequest {
    return WebhookDeliveryResponseDtoOutputRequestFromJSONTyped(json, false);
}

export function WebhookDeliveryResponseDtoOutputRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookDeliveryResponseDtoOutputRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'method': json['method'],
        'url': json['url'],
        'headers': json['headers'],
        'body': json['body'],
    };
}

export function WebhookDeliveryResponseDtoOutputRequestToJSON(json: any): WebhookDeliveryResponseDtoOutputRequest {
    return WebhookDeliveryResponseDtoOutputRequestToJSONTyped(json, false);
}

export function WebhookDeliveryResponseDtoOutputRequestToJSONTyped(value?: WebhookDeliveryResponseDtoOutputRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'method': value['method'],
        'url': value['url'],
        'headers': value['headers'],
        'body': value['body'],
    };
}

