/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WebhookEndpointResponseOutput
 */
export interface WebhookEndpointResponseOutput {
    /**
     * 
     * @type {string}
     * @memberof WebhookEndpointResponseOutput
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookEndpointResponseOutput
     */
    businessId: string;
    /**
     * 
     * @type {string}
     * @memberof WebhookEndpointResponseOutput
     */
    url: string;
    /**
     * 
     * @type {any}
     * @memberof WebhookEndpointResponseOutput
     */
    enabledEvents: any | null;
    /**
     * 
     * @type {boolean}
     * @memberof WebhookEndpointResponseOutput
     */
    active: boolean;
    /**
     * 
     * @type {number}
     * @memberof WebhookEndpointResponseOutput
     */
    consecutiveFailures: number;
    /**
     * 
     * @type {Date}
     * @memberof WebhookEndpointResponseOutput
     */
    lastFailureAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof WebhookEndpointResponseOutput
     */
    lastError: string | null;
    /**
     * 
     * @type {any}
     * @memberof WebhookEndpointResponseOutput
     */
    metadata: any | null;
    /**
     * 
     * @type {Date}
     * @memberof WebhookEndpointResponseOutput
     */
    createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof WebhookEndpointResponseOutput
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the WebhookEndpointResponseOutput interface.
 */
export function instanceOfWebhookEndpointResponseOutput(value: object): value is WebhookEndpointResponseOutput {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('businessId' in value) || value['businessId'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('enabledEvents' in value) || value['enabledEvents'] === undefined) return false;
    if (!('active' in value) || value['active'] === undefined) return false;
    if (!('consecutiveFailures' in value) || value['consecutiveFailures'] === undefined) return false;
    if (!('lastFailureAt' in value) || value['lastFailureAt'] === undefined) return false;
    if (!('lastError' in value) || value['lastError'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function WebhookEndpointResponseOutputFromJSON(json: any): WebhookEndpointResponseOutput {
    return WebhookEndpointResponseOutputFromJSONTyped(json, false);
}

export function WebhookEndpointResponseOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookEndpointResponseOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'businessId': json['businessId'],
        'url': json['url'],
        'enabledEvents': json['enabledEvents'],
        'active': json['active'],
        'consecutiveFailures': json['consecutiveFailures'],
        'lastFailureAt': (json['lastFailureAt'] == null ? null : new Date(json['lastFailureAt'])),
        'lastError': json['lastError'],
        'metadata': json['metadata'],
        'createdAt': (new Date(json['createdAt'])),
        'updatedAt': (new Date(json['updatedAt'])),
    };
}

export function WebhookEndpointResponseOutputToJSON(json: any): WebhookEndpointResponseOutput {
    return WebhookEndpointResponseOutputToJSONTyped(json, false);
}

export function WebhookEndpointResponseOutputToJSONTyped(value?: WebhookEndpointResponseOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'businessId': value['businessId'],
        'url': value['url'],
        'enabledEvents': value['enabledEvents'],
        'active': value['active'],
        'consecutiveFailures': value['consecutiveFailures'],
        'lastFailureAt': value['lastFailureAt'] == null ? value['lastFailureAt'] : value['lastFailureAt'].toISOString(),
        'lastError': value['lastError'],
        'metadata': value['metadata'],
        'createdAt': value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'].toISOString(),
    };
}

