/* tslint:disable */
/* eslint-disable */
/**
 * trile API
 * Subscription billing for Nepal — backend API
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WebhookEndpointResponseOutput } from './WebhookEndpointResponseOutput';
import {
    WebhookEndpointResponseOutputFromJSON,
    WebhookEndpointResponseOutputFromJSONTyped,
    WebhookEndpointResponseOutputToJSON,
    WebhookEndpointResponseOutputToJSONTyped,
} from './WebhookEndpointResponseOutput';

/**
 * 
 * @export
 * @interface WebhookEndpointPageResponseOutput
 */
export interface WebhookEndpointPageResponseOutput {
    /**
     * 
     * @type {Array<WebhookEndpointResponseOutput>}
     * @memberof WebhookEndpointPageResponseOutput
     */
    items: Array<WebhookEndpointResponseOutput>;
    /**
     * 
     * @type {string}
     * @memberof WebhookEndpointPageResponseOutput
     */
    nextCursor: string | null;
}

/**
 * Check if a given object implements the WebhookEndpointPageResponseOutput interface.
 */
export function instanceOfWebhookEndpointPageResponseOutput(value: object): value is WebhookEndpointPageResponseOutput {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('nextCursor' in value) || value['nextCursor'] === undefined) return false;
    return true;
}

export function WebhookEndpointPageResponseOutputFromJSON(json: any): WebhookEndpointPageResponseOutput {
    return WebhookEndpointPageResponseOutputFromJSONTyped(json, false);
}

export function WebhookEndpointPageResponseOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): WebhookEndpointPageResponseOutput {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(WebhookEndpointResponseOutputFromJSON)),
        'nextCursor': json['nextCursor'],
    };
}

export function WebhookEndpointPageResponseOutputToJSON(json: any): WebhookEndpointPageResponseOutput {
    return WebhookEndpointPageResponseOutputToJSONTyped(json, false);
}

export function WebhookEndpointPageResponseOutputToJSONTyped(value?: WebhookEndpointPageResponseOutput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(WebhookEndpointResponseOutputToJSON)),
        'nextCursor': value['nextCursor'],
    };
}

